$ IF F$MODE() .EQS. "BATCH" THEN SET PROCESS/NAME= "A New QPLOT"
$ SET DEFAULT [QPLOT.QPLOT.SOURCE]
$ PAS/NOLIST  MAKEHARD
$ LINK/NOMAP  MAKEHARD,QPLOT/L
$ RUN MAKEHARD
$ DELETE MAKEHARD.OBJ;*
$ DELETE MAKEHARD.EXE;*
$ @PAS HARDIO     QQHARD 'P1'
$ PURGE
