$ IF F$MODE() .EQS. "BATCH" THEN SET PROCESS/NAME= "A New QPLOT"
$ SET DEFAULT [QPLOT.QPLOT.SOURCE]
$ @PAS UTILITIES  QQSTAND 'P1'
$ @PAS IO_IMP     QQSTAND 'P1'
$ !
$ @PAS PLOT       QQPLOT 'P1'
$ @PAS PLOT3D     QQPLOT 'P1'
$ !
$ PURGE
