$ PAS BITMAP
$ LINK BITMAP,QLIBHOME:QPLOT/L
$ COPY BITMAP.EXE [OABJPD.QPLOT.HOME]*.*
$ COPY BITMAP.EXE [OABJPD.QPLOT.DISTRIB]*.*
$ PAS CI300
$ LINK CI300
$ COPY CI300.EXE [OABJPD.QPLOT.HOME]*.*
$ COPY CI300.EXE [OABJPD.QPLOT.DISTRIB]*.*
