DEL  MAIN.OBJ
DEL  MAIN.LST
FOR1 MAIN,MAIN,MAIN,NUL
PAS2
DEL  INPUT.OBJ
DEL  INPUT.LST
FOR1 INPUT,INPUT,INPUT,NUL
PAS2
DEL  COEFF.OBJ
DEL  COEFF.LST
FOR1 COEFF,COEFF,COEFF,NUL
PAS2
DEL  RUNS.OBJ
DEL  RUNS.LST
FOR1 RUNS,RUNS,RUNS,NUL
PAS2
DEL  TRIAL.OBJ
DEL  TRIAL.LST
FOR1 TRIAL,TRIAL,TRIAL,NUL
PAS2
DEL  RANMAT.OBJ
DEL  RANMAT.LST
FOR1 RANMAT,RANMAT,RANMAT,NUL
PAS2
DEL  VARCAL.OBJ
DEL  VARCAL.LST
FOR1 VARCAL,VARCAL,VARCAL,NUL
PAS2
DEL  PRICE.OBJ
DEL  PRICE.LST
FOR1 PRICE,PRICE,PRICE,NUL
PAS2
DEL  RUNHIS.OBJ
DEL  RUNHIS.LST
FOR1 RUNHIS,RUNHIS,RUNHIS,NUL
PAS2
DEL  RUNSTA.OBJ
DEL  RUNSTA.LST
FOR1 RUNSTA,RUNSTA,RUNSTA,NUL
PAS2
DEL  OUTPUT.OBJ
DEL  OUTPUT.LST
FOR1 OUTPUT,OUTPUT,OUTPUT,NUL
PAS2
