$!
$! Ad hoc command procedure to make the IBASE manual up.
$!
$ ON WARNING THEN CONTINUE
$ RUNOFF/CONTENTS/INDEX IBASEMAN.RNO
$!
$! do the table of contents
$!
$ TOC
IBASEMAN.BTC
N
N
99
99
N
Y
$ TCX
IBASEMAN.BIX
N
N
55
0
$ RUNOFF IBASEMAN.RNX
$ RUNOFF IBASEMAN.RNO
$ APPEND IBASEMAN.MEX IBASEMAN.MEM
$ DELETE IBASEMAN.RNX.*
$ DELETE IBASEMAN.MEX.*
$ DELETE IBASEMAN.BTC.*
$ DELETE IBASEMAN.BIX.*
$ DELETE IBASEMAN.RNT.*
$ DELETE 001TCX.TMP.*
$ PURGE IBASEMAN.MEM
