      FUNCTION DOT(X,Y)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION X(3),Y(3)
C
C********FUNCTION DOT COMPUTES THE DOT PRODUCT OF VECTORS X AND Y
C
      DOT=X(1)*Y(1)+X(2)*Y(2)+X(3)*Y(3)
      RETURN
      END
