      FUNCTION FNORM(X)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION X(3)
C
C********FUNCTION FNORM COMPUTES THE MAGNITUDE OF VECTOR X
C
      FNORM=DSQRT(X(1)**2+X(2)**2+X(3)**2)
      RETURN
      END
