      SUBROUTINE QUIKVIS0(IDTARG,IERR)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE QUIKVIS PROGRAM.  IT INITIALIZES PROGRAM
C PARAMETERS DIRECTLY OR VIA A CALL TO QUIKVIS0A.
C
C
C VARIABLE      DIM       TYPE I/O DESCRIPTION
C --------      ---       ---- --- -----------
C
C IDTARG      MAXTARGS     I*4  O  DESCRIBED IN QUIKVIS(=MAIN) PROLOGUE.
C
C IERR           1         I*4  O  ERROR RETURN FLAG
C                                  =0, NO ERROR
C                                  =OTHERWISE, ERROR.
C
C***********************************************************************
C
C BY C PETRUZZO/GFSC/742.   2/86.
C       MODIFIED.... CJP. 9/86.  CHANGED DOBARS2 AND KRELTIME DEFAULTS;
C                                SET DEFAULT FOR NEW VARIABLES
C                                DODETTABLE AND LEVDETFILE.
C
C***********************************************************************
C
      INCLUDE 'QUIKVIS.INC'
C
      INTEGER*4 IDTARG(MAXTARGS)
C
C
      IERR = 0
C
C THE FOLLOWING PARAMETERS ARE DEFINED IN QUIKVIS.INC; THEY ARE
C INITIALIZED HERE AND SOME ARE RESET LATER; COMMENTS IN QUIKVIS.INC
C TELL WHERE THEY ARE RESET.
C
      NEEDTIME = .FALSE.
C
      RAAN1 = 0.D0
      NUMRAAN = 49
      DELRAAN = TWOPI/(NUMRAAN-1)
C
      SOLTIM1 = 0.D0
      NUMSOLT = 25
      DELSOLT = 86400.D0/(NUMSOLT-1)
C
      TSTART = 0.D0
      DELTIME = 5.D0*86400.D0
      NUMTIMES = 1
C
      SMA = CONST(53) + 300.D0
      ECCMIN = 1.D-6
      ECC = ECCMIN ! REMOVES AMBIGUITIES ASSOCIATED WITH ARG PERIGEE
      ORBINCL = 28.5D0/DEGRAD
      ARGP = 0.D0
      VISMIN = 0.D0
C
      DOXYPLOT  =  .FALSE.
      DOXYPLOT1 =  .FALSE.
      DOXYPLOT2 =  .FALSE.
      TOPRINT =     .TRUE.
      TOPROMPT =   .FALSE.
      DODETAIL =   .FALSE.
      DOBARS1 =    .FALSE.
      DOBARS2 =    .FALSE.
      DODETTABLE = .FALSE.
      DOSUMMRY =    .TRUE.
      DOSURVEY =   .FALSE.
C
      NODEOPT = 1
      KSVYFREQ = 1
      KSVYOUT1 = 3
      KSVYOUT2 = 3
      KRELTIME = 2
      LEVDETFILE = 0
C
C
C READ OBSERVATION REQUIEMENTS FILE, LOAD TARGET ID'S, SET OBS REQMT
C PARAMETERS.
C
      CALL QUIKVIS999(1,R8DATA,I4DATA,L4DATA)
      CALL QUIKVIS0A(IDTARG,IERR)
      IF(IERR.NE.0) GO TO 9999
      CALL QUIKVIS999(-1,R8DATA,I4DATA,L4DATA)
C
 9999 CONTINUE
C
C WRAP UP. STORE DATA IN QUIKVIS999 ARRAYS FOR RETRIEVAL ELSEWHERE.
C
      CALL QUIKVIS999(1,R8DATA,I4DATA,L4DATA)
C
      RETURN
      END
