      SUBROUTINE QUIKVIS3
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE QUIKVIS PROGRAM.  IT INITIALIZES ALL
C QUIKVIS-UNIQUE ROUTINES NOT USED FOR PROGRAM INITIALIZATION OR
C USER INPUT.
C
C ROUTINES ARE INITIALIZED WHEN QVINIT'S LOAD THE GLOBAL VARIABLE VALUES
C INTO THEIR OWN LOCAL VARIABLES.
C
C QVINIT4, FOR EXAMPLE, IS AN ENTRY POINT IN QUIKVIS4.
C
C***********************************************************************
C
C BY C PETRUZZO/GFSC/742.   2/86.
C       MODIFIED.... 9/86. CJP. ADDED CALLS TO FOR NEWLY WRITTEN ENTRIES
C                               QVINIT5A2C3, ..5A3, ..5U, ..5V, AND ..5W
C
C
C***********************************************************************
C
      CALL QVINIT4
C
      CALL QVINIT5
        CALL QVINIT5A
          CALL QVINIT5A1
          CALL QVINIT5A2
            CALL QVINIT5A2A
            CALL QVINIT5A2B
            CALL QVINIT5A2C
              CALL QVINIT5A2C1
              CALL QVINIT5A2C2
              CALL QVINIT5A2C3
            CALL QVINIT5A2D
              CALL QVINIT5A2D1
          CALL QVINIT5A3
        CALL QVINIT5B
          CALL QVINIT5B1
            CALL QVINIT5B1A
            CALL QVINIT5B1B
            CALL QVINIT5B1X
        CALL QVINIT5U
        CALL QVINIT5V
        CALL QVINIT5W
        CALL QVINIT5X
        CALL QVINIT5Y
        CALL QVINIT5Z
C
      RETURN
      END
