      SUBROUTINE QUIKVIS5A2D(ITARG,IDTARG,TARGNAMES,KTARGTYP,TARGPARM)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE QUIKVIS PROGRAM.  IT IS THE DRIVER FOR
C THE OUTPUT ROUTINE QUIKVIS5A2D1 THAT GIVES TARGET AVAILABILITY INFO
C FOR INDIVIDUALLY SPECIFIED TARGETS.
C
C
C VARIABLE      DIM       TYPE I/O DESCRIPTION
C --------      ---       ---- --- -----------
C
C ITARG          1         I*4  I  INDEX OF THE TARGET FOR WHICH OUTPUT
C                                  IS TO BE GENERATED.
C
C IDTARG      MAXTARGS     I*4  I  DESCRIBED IN QUIKVIS(=MAIN) PROLOGUE.
C
C TARGNAMES   MAXTARGS    CH*16 I  DESCRIBED IN QUIKVIS(=MAIN) PROLOGUE.
C
C KTARGTYP    MAXTARGS     I*4  I  DESCRIBED IN QUIKVIS(=MAIN) PROLOGUE.
C
C TARGPARM NPARMS,MAXTARGS R*8  I  DESCRIBED IN QUIKVIS(=MAIN) PROLOGUE.
C
C***********************************************************************
C
C BY C PETRUZZO/GFSC/742.   2/86.
C       MODIFIED....
C
C***********************************************************************
C
      INCLUDE 'QUIKVIS.INC'
C
      CHARACTER*16 TARGNAMES(MAXTARGS)
      INTEGER*4 IDTARG(MAXTARGS)
      REAL*8 TARGPARM(NPARMS,MAXTARGS)
      INTEGER*4 KTARGTYP(MAXTARGS)
C
C
C GENERATE THE OUTPUT TABLE.  THERE ARE NUMTIMES COLUMNS IN THE TABLE,
C BUT ONLY 30 COLUMNS WILL FIT ON A PAGE.  IF NUMTIMES>30, WE NEED
C SUBTABLES.  SUB-TABLES CONTAIN 30 COLUMNS EACH AND SUBTABLE COLUMNS
C OVERLAP SO THAT THE LAST 5 COLUMNS ON ONE IS THE FIRST 5 ON THE NEXT.
C
      ITIME1 = 1
      ITIME2 = 0
C
      DO WHILE (ITIME2.LT.NUMTIMES)
C
        ITIME2 = MIN( (ITIME1+29),NUMTIMES )
C
        CALL QUIKVIS5A2D1(ITIME1,ITIME2,
     *       ITARG,IDTARG,TARGNAMES,KTARGTYP,TARGPARM)
C
        ITIME1 = ITIME2 - 4    ! THIS CAUSES THE OVERLAP
C
        END DO
C
C
      RETURN
C
C***********************************************************************
C
C
C**** INITIALIZATION CALL. PUT GLOBAL PARAMETER VALUES INTO THIS
C     ROUTINE'S LOCAL VARIABLES.
C
      ENTRY QVINIT5A2D
C
      CALL QUIKVIS999(-1,R8DATA,I4DATA,L4DATA)
      RETURN
C
C***********************************************************************
C
C
      END
