      SUBROUTINE QUIKVIS2A(IERR,IEND)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE QUIKVIS PROGRAM.  IT IS THE ROUTINE BY
C WHICH THE USER TELLS PGM WHETHER THIS IS AN INTERACTIVE RUN. PGM
C RESPONSE TO ERRORS IS DETERMINED BY THIS FLAG.  ALSO, FOR INTERACTIVE
C RUNS, MESSAGES ARE WRITTEN FROM QUIKVIS5A AND QUIKVIS5B ON THE PROMPT
C UNIT TO TELL THE USER HOW FAR THE RUN HAS PROGRESSED.
C
C VARIABLE DIM TYPE I/O DESCRIPTION
C -------- --- ---- --- -----------
C
C IERR      1   I*4  O  ERROR RETURN FLAG
C                       =0, NO ERRORS.
C                       = OTHERWISE, ERROR PRESENT.
C
C IEND      1   I*4  O  END-FILE FLAG
C                       =0, NO END-FILE ENCOUNTERED DURING USER INPUT.
C                       =1, END-FILE ENCOUNTERED.
C
C***********************************************************************
C
C BY C PETRUZZO/GFSC/742.   2/86.
C       MODIFIED....
C
C***********************************************************************
C
      INCLUDE 'QUIKVIS.INC'
C
C
      IERR = 0
      IEND = 1  ! WILL BE RESET TO ZERO IF READ IS DONE OK
C
C
      CALL QUIKVIS999(-1,R8DATA,I4DATA,L4DATA)
C
C
      WRITE(LUPROMPT,6756) 'ZERO'
 6756 FORMAT(//,
     *   ' ***************** USER GUIDE TABLE ',A,' *****************'/)
C
      KTEMP = KASKIT('IS THIS AN INTERACTIVE RUN ?',
     *            LUPROMPT,LUINPUT,5)
C
      IF(KTEMP.EQ.0) THEN
        INTERACTIVE = .FALSE.
        END IF
      IF(KTEMP.EQ.1) THEN
        INTERACTIVE = .TRUE.
        END IF
      IF(KTEMP.EQ.2) THEN  ! END FILE
        IEND = 1
        GO TO 9999
        END IF
      IF(KTEMP.EQ.3) THEN  ! MAX NUMBER OF INVALID REPLIES. ERROR COND.
        INTERACTIVE = .FALSE.   ! FORCES MAIN TO END THE PROGRAM
        IERR = 1
        GO TO 9999
        END IF
C
      IEND = 0
C
 9999 CONTINUE
C
C WRAP UP. STORE DATA IN QUIKVIS999 ARRAYS FOR RETRIEVAL ELSEWHERE.
C
      CALL QUIKVIS999(1,R8DATA,I4DATA,L4DATA)
C
      RETURN
      END
