      SUBROUTINE RDREQMT5A(LUREQMT,IEXP,CH8NAME,
     *           MAXEXP,MAXTGT,MAXREQEXP,MAXREQTGT,
     *           KEYREQEXP,REQEXP,REQTGT,NUMTGT,LUERR,IERR)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE TOSS REQUIREMENTS FILE READER PACKAGE. IT
C CALLS OTHER SUBROUTINES THAT READS EXPERIMENT DATA AND STORE IT IF
C REQUIRED(IE, WHEN IEXP>0). ERROR CHECKS ALSO.
C
C***********************************************************************
C
C BY C PETRUZZO GSFC/742  1/86
C        MODIFIED....
C
C***********************************************************************
C
      INCLUDE 'RDREQMT.INC'
C
      INTEGER*4   NUMTGT(MAXEXP),KEYREQEXP(MAXREQEXP)
      REAL*8      REQEXP(2,MAXREQEXP,MAXEXP)
      REAL*8      REQTGT(MAXREQTGT,MAXTGT,MAXEXP)
      CHARACTER*8 CH8NAME
C
      REAL*8 PARMS(MAXPARMS)
      REAL*8    R8VAL/1234567.D0/
      INTEGER*4 I4VAL/1234567/
C
C
      NUMTARGS = 0
      IERR = 0
C
C    READ EXPERIMENT-SPECIFIC DATA
C
      CALL RDREQMT5A1(LUREQMT,IEXP,MAXEXP,MAXREQEXP,
     *           CH8NAME,KEYREQEXP,REQEXP,LUERR,IERR)
      IF(IERR.NE.0) GO TO 9999
C  
C  
C    READ TARGET-SPECIFIC DATA
C
      CALL RDREQMT5A2(LUREQMT,IEXP,MAXEXP,MAXTGT,MAXREQTGT,
     *           CH8NAME,REQTGT,NUMTGT,LUERR,IERR)
      IF(IERR.NE.0) GO TO 9999
C
C
C WRAP UP.
C
 9999 CONTINUE
      RETURN
C
 9901 FORMAT(/,
     *   ' OBSERVATION REQUIREMENTS FILE READER. ERROR CONDITION.'/,
     *   (5X,A))    ! ERROR MESSAGE TEXT
      END
