      SUBROUTINE RDREQMT2(LUREQMT,LUPRINT)
C
C THIS ROUTINE IS PART OF THE TOSS REQUIREMENTS FILE READER PACKAGE. IT
C LISTS THE REQUIREMENTS FILE ON UNIT LUPRINT.
C
C***********************************************************************
C
C BY C PETRUZZO GSFC/742  1/86
C        MODIFIED....
C
C***********************************************************************
C
      CHARACTER*72 LINE
C
      REWIND LUREQMT
C
      WRITE(LUPRINT,1000) LUREQMT
      DO WHILE (I.EQ.I)
        LINE = ' '
        READ(LUREQMT,1001,END=100) LINE
        WRITE(LUPRINT,1002) LINE
        END DO
  100 CONTINUE
      WRITE(LUPRINT,1003)
C
 1000 FORMAT(//,
     *  ' EXPERIMENT REQUIREMENTS FILE LISTING:   (UNIT='I2,')'/)
 1001 FORMAT(A)
 1002 FORMAT(1X,A)
 1003 FORMAT(/,' END OF EXPERIMENT REQUIREMENTS FILE LISTING.'/)
C
      RETURN
      END
