      SUBROUTINE TGLOC08(NTARGS,KSYSNAT,KCENNAT,TARGPOS)
      IMPLICIT REAL*8 (A-H,O-Z)
C
C THIS ROUTINE IS PART OF THE TOSS TARGET LOCATION PACKAGE, TGLOC.
C SETS THE LOCATION HANDLES NON-SPECIFIC TARGETS(EX, IN-SITU TARGETS)
C TO ZERO.
C VAR     DIM    TYPE I/O DESCRIPTION
C ---     ---    ---- --- -----------
C
C NTARGS   1      I*4  I  NUMBER OF TARGETS TO BE PROCESSED.
C                         IF ZERO OR NEGATIVE, NONE ARE PROCESSED.
C
C KSYSNAT  1      I*4  O  IDENTIFIES THE NATURAL COORDINATE SYSTEM'S
C                         ORIENTATION.  IS SET TO 9999 TO INDICATE THE
C                         ORIENTATION IS IRRELEVANT.
C
C KCENNAT  1      I*4  O  IDENTIFIES THE NATURAL COORDINATE SYSTEM'S
C                         ORIGIN.  IS SET TO 9999 TO INDICATE THE ORIGIN
C                         IS IRRELEVANT.
C
C TARGPOS 3,NTARGS R*8 O  TARGPOS(-,I) IS THE POSITION VECTOR OF THE
C                         I'TH TARGET.  ALL LOCATIONS ARE SET TO ZERO.
C
C***********************************************************************
C
C BY C PETRUZZO, GSFC/742, 8/85.
C        MODIFIED....
C
C***********************************************************************
C
      REAL*8 TARGPOS(3,1)
C
      KSYSNAT = 9999
      KCENNAT = 9999
      IF(NTARGS.LE.0) GO TO 9999
C
C GET TARGET POSITION VECTOR IN 'NATURAL' SYSTEM.
C
      CALL MTXSETR8(TARGPOS,0.D0,3,NTARGS)  ! SET TO ZERO.
C
 9999 CONTINUE
      RETURN
      END
