      PROGRAM  MODFOL
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION A(16),B(8),AM(36),HM(24),Q(16),R(4),F(20),P(40),DUMMY(70
     *0),AC(100),BC(20),X(10)
      DIMENSION NA(2),NB(2),NAM(2),NHM(2),NQ(2),NR(2),NF(2),NP(2),NAC(2)
     *,NBC(2),IOP(5),NDUM(2),T(2),NX(2)
      LOGICAL  DISC,NEWT,STABLE,HIDENT,HMIDENT
C
C
C      INPUT HOLLERITH DATA FOR TITLE OF OUTPUT
      CALL RDTITL
C
C      INPUT COEFFICIENT MATRICES FOR PLANT AND MODEL
      CALL READ(5,A,NA,B,NB,AM,NAM,HM,NHM,X,NX)
C
C      DEFINE WEIGHTING MATRICES
      NQ(1)= NA(1)
      NQ(2)= NQ(1)
      NR(1)= NB(2)
      NR(2)= NR(1)
      CALL UNITY(Q,NQ)
      CALL SCALE(Q,NQ,Q,NQ,10.D0)
      CALL UNITY(R,NR)
C
C
C      COMPUTE MODEL-FOLLOWING GAINS
      IOP(1) = 1
      IOP(2) = 1
      IOP(3) =0
      IOP(4) = 0
      IOP(5) = 1
      DISC = .FALSE.
      NEWT = .FALSE.
      STABLE = .FALSE.
      HIDENT=.TRUE.
      HMIDENT = .FALSE.
C
      CALL EXMDFL(A,NA,B,NB,H,NH,AM,NAM,HM,NHM,Q,NQ,R,NR,F,NF,P,NP,HIDE
     *NT,HMIDENT,DISC,NEWT,STABLE,FNULL,ALPHA,IOP,DUMMY)
C
C
C      GENERATE COEFFICIENT MATRICES FOR INPUT TO TRANSIENT
C
C      RESPONSE SUBROUTINE
      NDUM(1) = NAM(1)
      NDUM(2) = NA(1)
      CALL NULL(DUMMY,NDUM)
      CALL JUXTR(A,NA,DUMMY,NDUM,AC,NAC)
      NDUM(1) = NA(1)
      NDUM(2) = NAM(1)
      CALL NULL(DUMMY,NDUM)
      N1 = NDUM(1)*NDUM(2) + 1
      CALL JUXTR(DUMMY,NDUM,AM,NAM,DUMMY(N1),NHM)
      N2=NHM(1)*NHM(2)+N1
      CALL JUXTC(AC,NAC,DUMMY(N1),NHM,DUMMY(N2),NDUM)
      CALL EQUATE(DUMMY(N2),NDUM,AC,NAC)
      NDUM(1) = NAM(1)
      NDUM(2) = NB(2)
      CALL NULL(DUMMY,NDUM)
      CALL JUXTR(B,NB,DUMMY,NDUM,BC,NBC)
C
C      COMPUTE TRANSIENT RESPONSE TO OBSERVE MODEL-FOLLOWING ACCURACY
      IOP(1) = 0
      IOP(2) = 0
      IOP(3) = 0
      T(1) = 50.
      T(2) = 2.
      CALL LNCNT(100)
      WRITE(6,100) NA(1),NAM(1)
  100 FORMAT('        IN THE TRAJECTORY OUTPUT TO FOLLOW THE FIRST',I4,
     *'COLUMNS CORRESPOND TO X TRANSPOSE',/,'   AND THE NEXT',I4,
     *' COLUMNS TO XM TRANSPOSE')
C
      CALL TRNSIT(AC,NAC,BC,NBC,H,NH,G,NG,F,NF,V,NV,T,X,NX,DISC,STABLE,
     *IOP,DUMMY)
C
C
      STOP
      END
