$!     PROCEDURE TO COMPILE ALL *.FOR FILES IN DEFAULT DIRECTORY
$ SET NOON
$ LOOP:
$   FILE = F$SEARCH("*.FOR")
$   IF FILE .EQS. ""  THEN GOTO END
$   WRITE SYS$OUTPUT FILE
$   FOR/LIST/CROSS_REFERENCE   'FILE'
$   GOTO LOOP
$ END:
$ SET ON
$ EXIT
