      INTEGER*4 FUNCTION HANDLER(SIGARGS,MECHARGS)
      INCLUDE '($FORDEF)'
      INCLUDE '($SSDEF)'
      INTEGER*4 SIGARGS(*),MECHARGS(5)

      IF (SIGARGS(2) .EQ. FOR$_ADJARRDIM) THEN
         HANDLER = SS$_CONTINUE
      ELSE
         HANDLER = SS$_RESIGNAL
      ENDIF

      RETURN
      END
