      SUBROUTINE RDDSK(PRINT)
      DOUBLE PRECISION RC,U,COM(1)
      COMMON RC,U,COM
      COMMON /PRAM/ NMAS,NHARM,NDISK,NDDISK
      COMMON /PARD/ NTPDSK(1)
      COMMON /PARE/ NTDDSK(1)
      COMMON /PARF/ NOPA1
      LOGICAL PRINT
      ID=4*NMAS+2*NHARM**2+NHARM+5*NDISK
      WRITE(6,700)
  700 FORMAT(// 16H0DISK INPUT DATA// 6H  DISK,6X,9H DENSITY,15H    DISK
     1 RADIUS,7X,8HLATITUDE, 6X,20HLONGITUDE  DISTANCE ,4HFROM/ 70X, 11H
     2MOON CENTER/)
      DO 150 IE=1,NDDISK
      I=IE+ID
      I1=I+NDDISK
      I2=I1+NDDISK
      I3=I2+NDDISK
      I4=I3+NDDISK
      I5=I4+NDDISK
      READ(5,30)A,B,C,D,E,F
C
C     A=DENSITY OF DISK
C     B=RADIUS OF DISK
C     C=LATITUDE OF DISK
C     D=LONGITUDE OF DISK
C     E=DISTANCE IN KILOMETERS OF THE CENTER OF THE DISK FROM THE CENTER
C       OF THE PRIMARY
C     F=THICKNESS OF DISK
      COM(I)=DBLE(A)
      COM(I1)=DBLE(B)
      COM(I2)=DBLE(C)
      COM(I3)=DBLE(D)
      COM(I4)=DBLE(E)
      COM(I5)=DBLE(F)
      IF(PRINT)WRITE(6,140)IE,COM(I),COM(I1),COM(I2),COM(I3),COM(I4),
     1COM(I5)
  140 FORMAT(I6,7D15.8)
  150 CONTINUE
      DO 100 I=1,NOPA1
  100 READ(5,180)NTPDSK(I),NTDDSK(I)
C
C     NTPDSK(I) INDICATES TYPE OF  PARAMETER I
C     I=1 DENSITY OF DISK
C     I=2 RADIUS OF DISK
C     I=3 LATITUDE OF CENTER OF DISK
C     I=4 LONGITUDE OF CENTER OF DISK
C     I=5 DISTANCE FROM CENTER OF MOON TO CENTER OF DISK
C     I=6 THICKNESS OF DISK
C      NTDDSK(I) DISK TO WHICH PARAMETER I APPLIES
  180 FORMAT(5X,2I5)
   30 FORMAT(3X,6E12.7)
      RETURN
      END
