$ !
$ ! *** LAST REVISED ON 21-JUL-1987 07:17:40.82
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]ACLEAR.COM
$ ! COMMAND FILE TO CLEAR SCREEN ON TEK4107 AND RESET MODE
$ WRITE SYS$OUTPUT "1*O"	! SELNAR
$ WRITE SYS$OUTPUT "%!0%!1"		! TEK 4107
$ WRITE SYS$OUTPUT "2[H[J[24B"
