$ ! CREATE A HELP LIBRARY FOR THE LONGLIB GRAPHICS LIBRARY
$ ! *** LAST REVISED ON  1-APR-1985 13:59:52.63
$ ! *** SOURCE FILE: [LONG.GRAPHICS.LONGLIB]HLPLIB.COM
$ LIBRARY/CREATE/HELP LONGLIB.HLB LONGLIB.HLP/HELP
$ EXIT
