$ !
$ ! *** LAST REVISED ON 12-MAY-1986 12:04:11.43
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]LASER.COM
$ ! command file for laser plotting--prints results
$ RUN LONGLOC:LASER			! LASER FILE CONVERTER
$ PRINT/QUE=LASER/NOFEED OUT.LIS	! PRINT FILE
$ EXIT
