C
C *** LAST REVISED ON  5-AUG-1987 14:44:29.22
C *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]LONGMISC.FOR
C
C ********************************************************************
C
C	MISC. ROUTINES FOR THE LONGLIB GRAPHICS LIBRARY
C
C	THESE ROUTINES MAY BE VERY MACHINE DEPENDENT
C
C ********************************************************************
C
	SUBROUTINE HELPME(HELP_STR)
C
C	ROUTINE TO INTERACTIVELY CALL THE LONGLIB GRAPHICS LIBRARY
C	HELP FACILITY FROM A PROGRAM.  USES THE VAX HELP LIBRARY ROUTINES.
C
C	HELP_STR IS THE INITIAL HELP STRING
C
	CHARACTER*(*) HELP_STR
C
	CHARACTER*20 HELP_LIB/'LONGLOC:LONGLIB.HLB'/
	INCLUDE '($HLPDEF)'
	INTEGER*4 LIB$PUT_OUTPUT,LIB$GET_INPUT,LBR$OUTPUT_HELP,STATUS
	EXTERNAL LIB$PUT_OUTPUT,LIB$GET_INPUT,LBR$OUTPUT_HELP
C
C	CALL LIBRARIAN ROUTINE
C
	STATUS=LBR$OUTPUT_HELP(LIB$PUT_OUTPUT,,HELP_STR,HELP_LIB,
     $		HLP$M_PROMPT,LIB$GET_INPUT)
	IF (.NOT.STATUS) CALL LIB$STOP(%VAL(STATUS))	! LIBRARY ERROR
C
	RETURN
	END
