$ ! command file for hi resolution raster scan converter
$ ! *** LAST REVISED ON 10-SEP-1987 11:14:35.19
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]NPLOTHI.COM
$ NAME = "FOR003.DAT"
$ FORNAM = "''F$SEARCH(NAME)'"
$ IF FORNAM .EQS. "" THEN GOTO ERROR
$ WRITE SYS$OUTPUT "USING FILE ''FORNAM'"
$ TRILGHI := $LONGLOC:TRILGHI		!RUN HI RESOLUTION RSC FOR TRILOG
$ TRILGHI 'FORNAM			!RUN HI RESOLUTION RSC FOR TRILOG
$ EXIT
$ ERROR:
$   WRITE SYS$OUTPUT "ERROR LOCATING ''NAME' PLOT FILE"
$ EXIT
