$ ! command file for low resolution raster scan converter--prints results
$ ! *** LAST REVISED ON 10-SEP-1987 11:13:51.23
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]NPLOTLO.COM
$ NAME = "FOR003.DAT"
$ FORNAM = "''F$SEARCH(NAME)'"
$ IF FORNAM .EQS. "" THEN GOTO ERROR
$ WRITE SYS$OUTPUT "USING FILE ''FORNAM'"
$ TRILGLO := $LONGLOC:TRILGLO
$ TRILGLO 'FORNAM			!RUN LOW RESOLUTION TRILOG
$ EXIT
$ ERROR:
$   WRITE SYS$OUTPUT "ERROR LOCATING ''NAME' PLOT FILE"
$ EXIT
