$ ! raster scan conversion for printronix printer
$ ! *** LAST REVISED ON 10-SEP-1987 11:15:14.19
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]NPLOT183.COM
$ NAME = "FOR003.DAT"
$ FORNAM = "''F$SEARCH(NAME)'"
$ IF FORNAM .EQS. "" THEN GOTO ERROR
$ WRITE SYS$OUTPUT "USING FILE ''FORNAM'"
$ PRNTRX := $LONGLOC:PRNTRX
$ PRNTRX 'FORNAM
$ EXIT
$ ERROR:
$   WRITE SYS$OUTPUT "ERROR LOCATING ''NAME' PLOT FILE"
$ EXIT
