$ ! command file for LA50 printer raster scan conversion
$ ! *** LAST REVISED ON 15-MAR-1988 08:59:35.09
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]PLOTLA50.COM
$ NAME = "''P1'"
$ IF "''P1'" .EQS. "" THEN NAME = "FOR003.DAT"
$ FORNAM = "''F$SEARCH(NAME)'"
$ IF FORNAM .EQS. "" THEN GOTO ERROR
$ WRITE SYS$OUTPUT "USING FILE ''FORNAM'"
$ RAST := $LONGLOC:LA50
$ RAST 'FORNAM
$ PRINT/QUE=LA50 OUT.LIS
$ EXIT
$ ERROR:
$   WRITE SYS$OUTPUT "ERROR LOCATING ''NAME' PLOT FILE"
$ EXIT
