$ ! command file for low resolution raster scan converter--prints results
$ ! *** LAST REVISED ON 10-SEP-1987 11:10:25.53
$ ! *** SOURCE FILE: [DL.GRAPHICS.LONGLIB]PLOTLO.COM
$ NAME = "''P1'"
$ IF "''P1'" .EQS. "" THEN NAME = "FOR003.DAT"
$ FORNAM = "''F$SEARCH(NAME)'"
$ IF FORNAM .EQS. "" THEN GOTO ERROR
$ WRITE SYS$OUTPUT "USING FILE ''FORNAM'"
$ RAST := $LONGLOC:TRILGLO
$ RAST 'FORNAM
$ PRINT/QUE=TRILOG OUT.LIS
$ EXIT
$ ERROR:
$   WRITE SYS$OUTPUT "ERROR LOCATING ''NAME' PLOT FILE"
$ EXIT
