      SUBROUTINE AUTPOW(Z,P,L,N,SIG,M,NS,IWIN,DELT,DELF)
      COMMON/DEBUG1/ IAFM(5)
      COMPLEX Z(1)
      DIMENSION P(1),AM(4)
      M1=M+1
      NS1=NS+1
      NSPEC=2*NS
      CALL AUTOCO(Z,P,L,N,SIG)
      IF(IAFM(4).EQ.0) GO TO 1975
      CALL PLTC(Z,1,M1,1,1,0,2)
 1975 CONTINUE
C
      DELF=1./(FLOAT(NSPEC)*DELT)
   16 FORMAT(14H DELF IN HZ = ,1PE10.3)
   17 FORMAT(1H1,30X,43H NORMALIZED POWER SPECTRAL DENSITY FUNCTION)
      WRITE(6,17)
      WRITE(6,16) DELF
      CALL POWERS(Z,M,NSPEC,IWIN)
      CALL PLTC(Z,1,NS1,1,1,0,0)
      RETURN
      END
