      BLOCK DATA
C
C     BLK8
C
C     TITLE DATA FOR PLOT HEADINGS
C
      COMPLEX*16 OPT2,TITLE
C
      COMMON/PLTHED/ OPT2(10),TITLE(450)
C
      COMPLEX*16 OPT1(10)
     * /'PSI1            ','THET1           ','PHI1            ',
     *  'OMEG1           ','OMEG2           ','OMEG3           ',
     * 'PHILD           ','NUTAT. ANGLE    ','EPSERR          ',
     * '                '/
C
      DATA OPT2
     * /'ALFAE           ','BETAE           ','GAMAE           ',
     *  'OMBC1           ','OMBC2           ','OMBC3           ',
     *  'PHILD           ','ROLL RATE       ','PITCH RATE      ',
     *  'YAW RATE        '/
C
      COMPLEX*16 FL11(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL12(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL13(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL14(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL15(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL16(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL17(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL18(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL19(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 FL20(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
C
      COMPLEX*16 DM11(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM12(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM13(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM14(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM15(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM16(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM17(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM18(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM19(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
      COMPLEX*16 DM20(6)
     * /'DISPL 1-2 PLANE ','RATE 1-2 PLANE  ','DISPL 1-3 PLANE ',
     *  'RATE 1-3 PLANE  ','TWIST 1 AXIS    ','RATE 1 AXIS     '/
C
      COMPLEX*16 FEMOD(9)
     * /'MODE1 1-2 PLANE ','MODE1 1-3 PLANE ',
     *  'MODE2 1-2 PLANE ','MODE2 1-3 PLANE ',
     *  'MODE3 1-2 PLANE ','MODE3 1-3 PLANE ',
     *  'MODE1 TWIST     ','MODE2 TWIST     ','MODE3 TWIST     '/
      COMPLEX*16 DEMOD(9)
     * /'MODE1 1-2 PLANE ','MODE1 1-3 PLANE ',
     *  'MODE2 1-2 PLANE ','MODE2 1-3 PLANE ',
     *  'MODE3 1-2 PLANE ','MODE3 1-3 PLANE ',
     *  'MODE1 TWIST     ','MODE2 TWIST     ','MODE3 TWIST     '/
C
      COMPLEX*16 GAREAD(6)
     * /'ACC. READING  1 ','ACC. READING  2 ','ACC. READING  3 ',
     *  'ACC. READING  4 ','ACC. READING  5 ','ACC. READING  6 '/
C
      COMPLEX*16 BDYINT(3)
     * /'BODY    IXX     ','BODY    IYY     ','BODY    IZZ     '/
      COMPLEX*16 HMMNTM(3)
     * /'RT.ASCENSION-HI ','DECLINATION-HI  ','MAGNITUDE OF HI '/
C
      COMPLEX*16 RTTNSN(10)
     * /'ROOT TENSION  1 ','ROOT TENSION  2 ','ROOT TENSION  3 ',
     *  'ROOT TENSION  4 ','ROOT TENSION  5 ','ROOT TENSION  6 ',
     *  'ROOT TENSION  7 ','ROOT TENSION  8 ','ROOT TENSION  9 ',
     *  'ROOT TENSION  10'/
C
      COMPLEX*16 RTBNDM(20)
     *   /'1-2 PLANE BNDM 1','1-3 PLANE BNDM 1',
     *    '1-2 PLANE BNDM 2','1-3 PLANE BNDM 2',
     *    '1-2 PLANE BNDM 3','1-3 PLANE BNDM 3',
     *    '1-2 PLANE BNDM 4','1-3 PLANE BNDM 4',
     *    '1-2 PLANE BNDM 5','1-3 PLANE BNDM 5',
     *    '1-2 PLANE BNDM 6','1-3 PLANE BNDM 6',
     *    '1-2 PLANE BNDM 7','1-3 PLANE BNDM 7',
     *    '1-2 PLANE BNDM 8','1-3 PLANE BNDM 8',
     *    '1-2 PLANE BNDM 9','1-3 PLANE BNDM 9',
     *    '1-2 PLANE BNDM10','1-3 PLANE BNDM10'/
C
      COMPLEX*16 SANGLS(2)
     *  /'BODY SUN ANG-ALP','BODY SUN ANG-DEC'/
C
      COMPLEX*16 FIELDM(3)
     *  /'MAGNET.VECTOR-B1','MAGNET.VECTOR-B2','MAGNET.VECTOR-B3'/
C
      COMPLEX*16 HHHVAL/'HAMILTONIAN     '/
      COMPLEX*16 BNDMAG(10)
     *   /'MAG. BNDM-ELEM 1',
     *    'MAG. BNDM-ELEM 2',
     *    'MAG. BNDM-ELEM 3',
     *    'MAG. BNDM-ELEM 4',
     *    'MAG. BNDM-ELEM 5',
     *    'MAG. BNDM-ELEM 6',
     *    'MAG. BNDM-ELEM 7',
     *    'MAG. BNDM-ELEM 8',
     *    'MAG. BNDM-ELEM 9',
     *    'MAG. BNDM-ELEM10'/
C
      COMPLEX*16 WHLSPD(3)
     * /'AXIS 1 WHL. SPD.','AXIS 2 WHL. SPD.','AXIS 3 WHL. SPD.'/
C
      COMPLEX*16 EXTMOM(3)
     * /'EXTERNAL MOMENT1','EXTERNAL MOMENT2','EXTERNAL MOMENT3'/
C
      COMPLEX*16 HMBODY(3)
     * /'AXIS 1  MOMENTUM','AXIS 2  MOMENTUM','AXIS 3  MOMENTUM'/
C
      COMPLEX*16 CONSYS(20)
     */'CONT. SYS. INT 1','CONT. SYS. INT 2','CONT. SYS. INT 3',
     * 'CONT. SYS. INT 4','DEB NUTATION ANG','CONT. SYS. INT 6',
     * 'CONT. SYS. INT 7','CONT. SYS. INT 8','CONT. SYS. INT 9',
     * 'CONT. SYS. INT10','CONT. SYS. INT11','CONT. SYS. INT12',
     * 'CONT. SYS. INT13','CONT. SYS. INT14','CONT. SYS. INT15',
     * 'CONT. SYS. INT16','CONT. SYS. INT17','CONT. SYS. INT18',
     * 'CONT. SYS. INT19','CONT. SYS. INT20'/
C
      COMPLEX*16 SBDTIT(9)
     1/'GAMMA SEC. BODY ','ALPHA SEC. BODY ','BETA SEC. BODY  ',
     2 'GAMMAD SEC. BODY','ALPHAD SEC. BODY','BETAD SEC. BODY ',
     3 'OMEGA1 SEC. BODY','OMEGA2 SEC. BODY','OMEGA3 SEC. BODY'/
C
      COMPLEX*16 ACFTIT(3)
     1/'SENSOR OUTPUT   ','FILTER OUTPUT   ','FILTER W-OUTPUT '/
C
      COMPLEX*16 PRODIN(3)
     * /'BODY    IXY     ','BODY    IXZ     ','BODY    IYZ     '/
C
      COMPLEX*16 TSLOPS(40)
     * /'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ',
     *  'SLOPE 1-2 PLANE ','SLOPE 1-3 PLANE ','SLOPE 1-2 PLANE ',
     *  'SLOPE 1-3 PLANE '/
C
      COMPLEX*16 SLPMOD(6)
     *  /'MODE1 1-2 SLOPE ','MODE1 1-3 SLOPE ','MODE2 1-2 SLOPE ',
     *  'MODE2 1-3 SLOPE ','MODE3 1-2 SLOPE ','MODE3 1-3 SLOPE '/
C
      COMPLEX*16 GIMBLE(4)
     * /'GIMBLE AZIMUTH  ','GIMBLE AZIM RATE','GIMBLE ELEVATION',
     *  'GIMBLE ELEV RATE'/
C
      COMPLEX*16 DIMBLE(4)
     * /'GIMBLE AZIMUTH  ','GIMBLE AZIM RATE','GIMBLE ELEVATION',
     *  'GIMBLE ELEV RATE'/
C
      COMPLEX*16 PLATCS(9)
     * /'FILTER MAG 1    ','FILTER MAG 2    ','FILTER MAG 3    ',
     *  'AZIMUTH ERROR   ','ELEVATION ERROR ','AZIM P I D OUTPT',
     *  'ELEV P I D OUTPT','AZIM MOTOR TRQUE','ELEV MOTOR TRQUE'/
C
      COMPLEX*16 DLATCS(9)
     * /'FILTER MAG 1    ','FILTER MAG 2    ','FILTER MAG 3    ',
     *  'AZIMUTH ERROR   ','ELEVATION ERROR ','AZIM P I D OUTPT',
     *  'ELEV P I D OUTPT','AZIM MOTOR TRQUE','ELEV MOTOR TRQUE'/
C
      COMPLEX*16 ELTEMP(10)
     *   /'AVG. TEMP-ELEM 1',
     *    'AVG. TEMP-ELEM 2',
     *    'AVG. TEMP-ELEM 3',
     *    'AVG. TEMP-ELEM 4',
     *    'AVG. TEMP-ELEM 5',
     *    'AVG. TEMP-ELEM 6',
     *    'AVG. TEMP-ELEM 7',
     *    'AVG. TEMP-ELEM 8',
     *    'AVG. TEMP-ELEM 9',
     *    'AVG. TEMP-ELEM10'/
C
      COMPLEX*16 AWHSPD(3)
     * /'AXIS 1 WHL. SPD.','AXIS 2 WHL. SPD.','AXIS 3 WHL. SPD.'/
C
      COMPLEX*16 FILOUT(3)
     * /'AXIS 1  FILT OUT','AXIS 2  FILT OUT','AXIS 3  FILT OUT'/
C
      COMPLEX*16 AILOUT(2)
     * /'ARB AXS FILT OUT','ARB AXS WHL. SPD'/
C
      COMPLEX*16 SPARES(87)
     * /87*'                '/
C
      COMPLEX*16 ENVMOM(9)
     * /'GR. GR. MOMENT 1','GR. GR. MOMENT 2','GR. GR. MOMENT 3',
     *  'SOL PR. MOMENT 1','SOL PR. MOMENT 2','SOL PR. MOMENT 3',
     *  'AIR DR. MOMENT 1','AIR DR. MOMENT 2','AIR DR. MOMENT 3'/
C
      COMPLEX*16 SAGLOT(2)
     * /'SNGL AXS GMB ANG','SNGL AXS GMB RT.'/
C
      COMPLEX*16 SAPLCS(6)
     * /'FILTER VECTOR 1 ','FILTER VECTOR 2 ','FILTER VECTOR 3 ',
     *  'ANGLE ERROR     ','ANGL P I D OUTPT','ANGL MOTOR TRQUE'/
C
      COMPLEX*16 REACTR(6)
     * /'REACTN MOMENT  1','REACTN MOMENT  2','REACTN MOMENT  3',
     *  'MOTOR  TORQUE  1','MOTOR  TORQUE  2','MOTOR  TORQUE  3'/
C
C
      EQUIVALENCE (TITLE(1),OPT1(1))
C
      EQUIVALENCE (TITLE(11),FL11(1)),(TITLE(17),FL12(1))
     * ,(TITLE(23),FL13(1)),(TITLE(29),FL14(1)),(TITLE(35),FL15(1))
     * ,(TITLE(41),FL16(1)),(TITLE(47),FL17(1)),(TITLE(53),FL18(1))
     * ,(TITLE(59),FL19(1)),(TITLE(65),FL20(1))
C
      EQUIVALENCE (TITLE(71),DM11(1)),(TITLE(77),DM12(1))
     * ,(TITLE(83),DM13(1)),(TITLE(89),DM14(1)),(TITLE(95),DM15(1))
     * ,(TITLE(101),DM16(1)),(TITLE(107),DM17(1)),(TITLE(113),DM18(1))
     * ,(TITLE(119),DM19(1)),(TITLE(125),DM20(1))
C
      EQUIVALENCE (TITLE(131),FEMOD(1)),(TITLE(140),DEMOD(1))
     * ,(TITLE(149),GAREAD(1)),(TITLE(155),BDYINT(1))
     * ,(TITLE(158),HMMNTM(1)),(TITLE(161),RTTNSN(1))
     * ,(TITLE(171),RTBNDM(1)),(TITLE(191),SANGLS(1))
     * ,(TITLE(193),FIELDM(1)),(TITLE(196),HHHVAL)
     * ,(TITLE(197),BNDMAG(1))
C
      EQUIVALENCE (TITLE(207),WHLSPD(1))
C
      EQUIVALENCE (TITLE(210),EXTMOM(1)),(TITLE(213),HMBODY(1))
C
      EQUIVALENCE (TITLE(216),CONSYS(1))
C
      EQUIVALENCE (TITLE(236),SBDTIT(1)),(TITLE(245),ACFTIT(1))
C
      EQUIVALENCE (TITLE(248),PRODIN(1))
      EQUIVALENCE (TITLE(251),TSLOPS(1))
      EQUIVALENCE (TITLE(291),SLPMOD(1))
      EQUIVALENCE (TITLE(297),GIMBLE(1))
      EQUIVALENCE (TITLE(301),PLATCS(1))
      EQUIVALENCE (TITLE(310),DIMBLE(1))
      EQUIVALENCE (TITLE(314),DLATCS(1))
      EQUIVALENCE (TITLE(323),FILOUT(1))
      EQUIVALENCE (TITLE(326),AWHSPD(1))
      EQUIVALENCE (TITLE(329),AILOUT(1))
      EQUIVALENCE (TITLE(331),ELTEMP(1))
      EQUIVALENCE (TITLE(341),SAGLOT(1))
      EQUIVALENCE (TITLE(343),SAPLCS(1))
      EQUIVALENCE (TITLE(349),ENVMOM(1))
      EQUIVALENCE (TITLE(358),REACTR(1))
      EQUIVALENCE (TITLE(364),SPARES(1))
C
C
      END
