      SUBROUTINE CHECK(QA,QB,NX)
C     ZEROS OUT ANTENNA DEFLECTIONS AND VELOCITIES IF NONE ARE INPUT
      IMPLICIT REAL*8 (A-H,O-Z)
C
      DIMENSION QA(10,3),QB(10,3)
C
      DO 20 I=1,10
      DO 10 J=1,3
      QA(I,J)=0.0D0
      QA(I,J)=QB(I,J)
      IF(DABS(QA(I,J)).LE.10.D-30) QA(I,J)=0.0D0
   10 CONTINUE
   20 CONTINUE
      RETURN
      END
