      SUBROUTINE CSIC(ITEST,T)
C     CONTROL SYSTEM INITIAL CONDITIONS
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON /ADSTAT/DER(150),DEP(150)
C
      COMMON/CNOISE/VLAST(10),VGOOD(10),VNOW(10),T1,T2
C
      COMMON/CSBNDS/CSUP(20),CSDN(20),GNIC(10)
C
      COMMON /CSTAT/SVCS(20),SVCDOT(20)
C
      COMMON/ICNTRL/KNTRL(10)
C
      COMMON/ICSADM/LDUM,IRAND,NCHAN
C
      COMMON /JCNTRL/NCNTRL,MCNTRL,MAPCNT(20)
C
      COMMON/IMAIN1/ IDATE,LSAVE,INOPT,IPLOT,NUMEQS,IPLTPE,IORB,ITAPE
C
      COMMON/SCSTAT/SSVCS(20)
C
      COMMON/XIN4  /UP(150),DN(150),BNDS(22)
C
      IF(ITEST.EQ.2) GO TO 200
      IRAND=KNTRL(9)
      NCHAN=KNTRL(10)
      T1=T
      T2=T
      DO 50 I=1,10
      VLAST(I)=GNIC(I)
      VGOOD(I)=GNIC(I)
      VNOW(I)=0.0D0
   50 CONTINUE
C      LOAD SYSTEM STATE VECTOR WITH CONTROL SYSTEM STATE
      DO 100 I=1,NCNTRL
      J=MAPCNT(I)
      SSVCS(J)=SVCS(J)
      UP(I+MCNTRL)=CSUP(J)
      DN(I+MCNTRL)=CSDN(J)
100   DEP(I+MCNTRL)=SVCS(J)
      RETURN
C
  200 CONTINUE
      DO 300 I=1,NCNTRL
      J=MAPCNT(I)
      SVCS(J)=SSVCS(J)
  300 CONTINUE
      RETURN
      END
