      SUBROUTINE DEREQ1(QDPEND,TIME,QDERIV)
C     BUFFER SUBROUTINE BETWEEN ADMIMP & DEREQ
C          DEPENDENT VARIABLES ARE SUPPLIED IN QDEPEND,
C          DERIVATIVES ARE RETURNED VIA QDERIV
C     DEREQ TAKES ITS VALUES FROM THE COMMON BLOCK VARBLS
C
      IMPLICIT REAL*8(A-H,O-Z)
      COMMON/ICSADM/ LADAM
      COMMON/IMAIN1/ IDATE,LSAVE,INOPT,IPLOT,NUMEQS,IPLTPE,IORB,ITAPE
      COMMON/RPOOL1/ RHOK(10),TIM1,SA(3,3),FM1(3,3),ZLK(10),OMEG(3),
     .               ZLKP(10),ZLKDP(10),CMAT(3,3),GBAR(3,3),YBCM(3),
     .               ZBZK(3,10),FCM(3,3),DTO,PHID,PHI
      COMMON/VARBLS/ DEPEND(150),DERIV(150)
C
      DIMENSION QDPEND(2),QDERIV(2)
C
C
C      LOAD THE STATE VARIABLES
      TIM1=TIME
      DO 10 I=1,NUMEQS
   10 DEPEND(I)=QDPEND(I)
C
C     COMPUTE DERIVATIVES
      CALL DEREQ
C
C     COLLECT THE RESULTS
      DO 250 J=1,NUMEQS
250   QDERIV(J)=DERIV(J)
C
      DO 270 I=1,6
      QDPEND(I)=DEPEND(I)
  270 CONTINUE
C
      IF(LADAM.NE.1) GO TO 300
C
      DO 260 J=7,NUMEQS
      QDPEND(J)=DEPEND(J)
  260 CONTINUE
C
  300 CONTINUE
C
      RETURN
      END
