      SUBROUTINE DROUT(A,B,AD,BD,NDAMPR)
C
C        'DROUT' CHECKS FOR MAXIMUM MODE SHAPE AND SAVES FOR UPPER
C        LIMIT TO OUTPUT DEFLECTIONS
C
      IMPLICIT REAL * 8 (A-H,O-Z)
C
      COMMON/IPOOL1/ IGRAV,IDAMP,IK,K1,ITIM,IAB,IAPS,IBB,IBPS,NK(10),
     .               LK(10),LLK(10)
C
      DIMENSION A(10,3),B(10,3),AD(10,3),BD(10,3)
C
C
      N=NDAMPR
      M=0
      DO 10 I=1,N
   10 M=MAX0(NK(I),M)
C
      CALL AVAL('DIN     ',3,A,10,N,M,2)
C
      CALL AVAL('DINDOT  ',6,AD,10,N,M,2)
C
      CALL AVAL('DOUT    ',4,B,10,N,M,2)
C
      CALL AVAL('DOUTDT  ',6,BD,10,N,M,2)
C
C
      RETURN
      END
