      SUBROUTINE ECHOA
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 ISUBD,JARRAY,J2,J3,J4,J22,NSUBX
      INTEGER*4 ACNTRL,DDPLY
C
      COMMON/ICNTRL/KNTRL(10)
      COMMON/CSTAT /SVIC(20),SVDOT(20),CPARM(43)
      COMMON/CNBODY/ J2,J3,J4,J22,ZJ20,ZMU,WWO,FLAT,AEARTH
      COMMON/IMAIN1/ IDATE,LSAVE,INOPT,IPLOT,NUMEQS,IPLTPE,IORB,ITAPE
      COMMON/MOMENT/ ACNTRL,IVISCS,IATTDE,IMGMTS,IWHEEL,NPULSE
      COMMON/PLOTIT/ XMIN(11),XMAX(11),YMIN(11),YMAX(11),IFSCAL,
     .               KPLOTS(253)
      COMMON/CWHEEL/VW(3),VSUR(3),VSDR(3)
      COMMON/DMMNT1/ ZKBM(6),FMAK(10),FMBK(10),ARTETA(3),CMTORK(3),
     .               ITORK,IBENDM,ITENSE,ITNS1
      COMMON/PWHEEL/ XMOMIN(3),DVMOM(3),VMOM(3)
      COMMON/RATTDE/ DTMXA,PXI,PXO,EIT,REFTIM,TMX1,TMX2,CMX,ISW
      COMMON/RMAIN1/ DELTAT,FACTOR,FREQ,TSTOP,DELMIT,
     .               UPBND(150),DNBND(150)
      COMMON/RMGNTC/ SMAGI(3),DPMAG(3),SFMAG,MAGFLD
      COMMON/RSUNCL/ WE,TVER,ECLPTC
      COMMON/RVISCS/ NSUBX(3),YARRAY(3),RADTBE,VISCTY,RADRNG,DENSTY,
     .               JARRAY(3),SSUBY,OMEGL,ISUBD
      COMMON/VECTRS/ XSAT(3),XSATDT(3),AD(3)
      COMMON/XIN3  / ALFAEK(10),BETAEK(10),GAMAEK(10),ETTAD,ZETTAD
      COMMON/ZSPINR/ DTZMA,PZDT,CMZO,ISPIN3,JSPIN
      COMMON/IKPLER/IKPLR
      COMMON/ITCNTL/IPULSE,ISPLSE,KPULSE,ITSW,IOTSW,IPLPRP
      COMMON/THRUST/TV(3,2),TLOC(3,2),TTIM(4,2),TPAR(4,2),REF(2)
      COMMON/XKPLER/AS,E,F,EI,BW,W
      COMMON/IACC/IACOMP,IHUBAC,ITIPAC
      COMMON/NUMACC/NUMHUB
      COMMON/ACCHUB/ YHUB(3,6),HUBACC(3,6),ACCRED(6),ALFAEA(6),
     .  BETAEA(6),GAMAEA(6),DKAT(3,3,6)
      DIMENSION HED9(5),HED10(5),HED11(5),HED12(5),
     1       HED13(5),HED14(5),HED18(5),HED19(5),HED20(5),HED21(5)
      DIMENSION HED25(5),HED26(5),HED28(5)
      DIMENSION HED15(5)
      DATA HED9 /'NUTATION',' VISCOUS',' RING DA','MPER OPT','ION     '/
      DATA HED10/'ATTITUDE',' CONTROL',' MOMENT ','OPTION  ','        '/
      DATA HED11/'MOMENTUM',' WHEEL O','PTION   ','        ','        '/
      DATA HED12/'MAGNETIC',' MOMENT ','OPTION  ','        ','        '/
      DATA HED13/'EARTH PR','OPERTIES','        ','        ','        '/
      DATA HED14/'TORQUE A','BOUT BOD','Y AXIS  ','        ','        '/
      DATA HED15/'DEB CONT','ROL SYST','EM PARAM','ETERS   ','        '/
      DATA HED18/'ORBITAL ','INPUT CO','NTROL   ','        ','        '/
      DATA HED19/'SPIN AXI','S MOMENT','        ','        ','        '/
      DATA HED20/'PRINTER ','PLOT CON','TROL    ','        ','        '/
      DATA HED21/'INTERNAL',' ORBIT S','TARTING ','VECTORS ','        '/
      DATA HED25/'THRUSTIN','G PARAME','TERS    ','        ','        '/
      DATA HED26/'KEPLERIA','N ORBIT ','PARAMETE','RS      ','        '/
      DATA HED28/'NUMBER O','F ACCELE','ROMETER ','IN HUB  ','        '/
      IF(ITORK.EQ.0) GO TO 40
      CALL HVAL(HED14)
      CALL IVAL('ITORK   ',5,ITORK,0,0,0)
      CALL FVAL('CMTORK  ',6,CMTORK,3,0,1)
 40   CONTINUE
      IF(IVISCS.EQ.0) GO TO 50
C
      CALL HVAL(HED9)
      CALL IVAL('IVISCS  ',6,IVISCS,0,0,0)
      CALL FVAL('VISCTY  ',6,VISCTY,0,0,0)
      CALL FVAL('RADTBE  ',6,RADTBE,0,0,0)
      CALL FVAL('RADRNG  ',6,RADRNG,0,0,0)
      CALL FVAL('DENSTY  ',6,DENSTY,0,0,0)
      CALL FVAL('ZETTAD  ',6,ZETTAD,0,0,0)
      CALL FVAL('ETTAD   ',5,ETTAD,0,0,0)
      CALL FVAL('YARRAY  ',6,YARRAY,3,0,1)
      CALL FVAL('OMEGL   ',5,OMEGL,0,0,0)
C
   50 IF(IATTDE.EQ.0) GO TO 55
C
      CALL HVAL(HED10)
      CALL IVAL('IATTDE  ',6,IATTDE,0,0,0)
      CALL FVAL('DTMXA   ',5,DTMXA,0,0,0)
      CALL FVAL('PXI     ',3,PXI,0,0,0)
      CALL FVAL('PXO     ',3,PXO,0,0,0)
      CALL FVAL('CMX     ',3,CMX,0,0,0)
      CALL IVAL('NPULSE  ',6,NPULSE,0,0,0)
C
   55 IF(ISPIN3.EQ.0) GO TO 60
C
      CALL HVAL(HED19)
      CALL IVAL('ISPIN3  ',6,ISPIN3,0,0,0)
      CALL FVAL('DTZMA   ',5,DTZMA,0,0,0)
      CALL FVAL('PZDT    ',4,PZDT,0,0,0)
      CALL FVAL('CMZO    ',4,CMZO,0,0,0)
 60   IF(IHUBAC.EQ.0) GO TO 62
      CALL HVAL(HED28)
      CALL IVAL('NUMHUB  ',6,NUMHUB,0,0,0)
      CALL FVAL('YHUB    ',4,YHUB,3,NUMHUB,2)
      CALL FVAL('ALFAEA  ',6,ALFAEA,NUMHUB,0,1)
      CALL FVAL('BETAEA  ',6,BETAEA,NUMHUB,0,1)
      CALL FVAL('GAMAEA  ',6,GAMAEA,NUMHUB,0,1)
 62   IF(IPULSE.EQ.0) GO TO 65
      CALL HVAL(HED25)
      CALL IVAL('IPULSE  ',6,IPULSE,0,0,0)
      CALL IVAL('ISPLSE  ',6,ISPLSE,0,0,0)
      CALL IVAL('IPLPRP  ',6,IPLPRP,0,0,0)
      CALL FVAL('TVECTR  ',6,TV,3,IPLPRP,2)
      CALL FVAL('TLOCAT  ',6,TLOC,3,IPLPRP,2)
      CALL FVAL('TTIMES  ',6,TTIM,4,IPLPRP,2)
      CALL FVAL('TPARAM  ',6,TPAR,4,IPLPRP,2)
      CALL FVAL('REFANG  ',6,REF,IPLPRP,0,1)
C
 65   IF(IWHEEL.EQ.0) GO TO 70
C
      CALL HVAL(HED11)
      CALL IVAL('IWHEEL  ',6,IWHEEL,0,0,0)
      CALL FVAL('XMOMIN  ',6,XMOMIN,3,0,1)
      CALL FVAL('VMOM    ',4,VMOM,3,0,1)
      CALL FVAL('DVMOM   ',5,DVMOM,3,0,1)
      CALL FVAL('VSUR    ',4,VSUR,3,0,1)
      CALL FVAL('VSDR    ',4,VSDR,3,0,1)
C
      IF(KNTRL(1).EQ.0) GO TO 70
C
      CALL HVAL(HED15)
      CALL IVAL('KNTRL   ',5,KNTRL,10,0,1)
      CALL FVAL('CPARM   ',5,CPARM,43,0,1)
      CALL FVAL('CSICS   ',5,SVIC,20,0,1)
C
   70 CONTINUE
C
      CALL ECHOSB
C
      CALL ECHOGP
C
      CALL ECHOGM
C
      CALL ECHOPC
C
      IF(IMGMTS.EQ.0) GO TO 75
C
      CALL HVAL(HED12)
      CALL IVAL('IMGMTS  ',6,IMGMTS,0,0,0)
      CALL FVAL('DPMAG   ',5,DPMAG,3,0,1)
      CALL IVAL('MAGFLD  ',6,MAGFLD,0,0,0)
C
   75 IF(IPLOT.EQ.0) GO TO 80
C
      CALL HVAL(HED20)
      CALL IVAL('IPLOT   ',5,IPLOT,0,0,0)
      CALL IVAL('IFSCAL  ',6,IFSCAL,0,0,0)
      CALL FVAL('XMIN    ',4,XMIN,11,0,1)
      CALL FVAL('XMAX    ',4,XMAX,11,0,1)
      CALL FVAL('YMIN    ',4,YMIN,11,0,1)
      CALL FVAL('YMAX    ',4,YMAX,11,0,1)
C
 80   CONTINUE
C
      CALL HVAL(HED13)
      CALL FVAL('AEARTH  ',6,AEARTH,0,0,0)
      CALL FVAL('ZMU     ',3,ZMU,0,0,0)
      CALL FVAL('ZJ20    ',4,ZJ20,0,0,0)
      CALL FVAL('FLAT    ',4,FLAT,0,0,0)
      CALL FVAL('WWO     ',3,WWO,0,0,0)
      CALL FVAL('WE      ',2,WE,0,0,0)
      CALL FVAL('J2      ',2,J2,0,0,0)
      CALL FVAL('J3      ',2,J3,0,0,0)
      CALL FVAL('J4      ',2,J4,0,0,0)
      CALL FVAL('J22     ',3,J22,0,0,0)
      CALL FVAL('TVER    ',4,TVER,0,0,0)
      CALL FVAL('ECLPTC  ',6,ECLPTC,0,0,0)
C
      CALL HVAL(HED18)
      CALL IVAL('IORB    ',4,IORB,0,0,0)
      CALL IVAL('ITAPE   ',5,ITAPE,0,0,0)
C
      IF(IORB.NE.0) RETURN
      IF(IKPLR.EQ.0) GO TO 200
      CALL HVAL(HED26)
      CALL FVAL('AS      ',2,AS,0,0,0)
      CALL FVAL('E       ',1,E,0,0,0)
      CALL FVAL('EI      ',2,EI,0,0,0)
      CALL FVAL('F       ',1,F,0,0,0)
      CALL FVAL('BW      ',2,BW,0,0,0)
      CALL FVAL('W       ',1,W,0,0,0)
      GO TO 210
 200  CONTINUE
C
      CALL HVAL(HED21)
      CALL FVAL('XSAT    ',4,XSAT,3,0,1)
      CALL FVAL('XSATDT  ',6,XSATDT,3,0,1)
 210  CONTINUE
      RETURN
      END
