      SUBROUTINE ECHOGD
C
      IMPLICIT REAL*8(A-H,O-Z)
C
C     SUBROUTINE ECHOGD IS THE ECHO ROUTINE TO PRINT GROUND
C     TESTING RELATED INPUT VARIABLES FOR CHECKING
C
C     WRITTEN BY K. YONG OF COMPUTER SCIENCES CORP IN MARCH 1976
C
      COMMON/GRNTST/ALFAEG,DELTAG,PHASEG,ALTUDE,OMGY(3),
     *      GACC(3),GLOCAT(3),IGRUND,IALTUD,IGASBR
C
      COMMON/GMATRX/GMAX(3,3),GMAXT(3,3)
C
      COMMON/HEAD22/HEAD1(5),HEAD2(5),ILINE
C
      DIMENSION HED0(5),HED1(5),HED2(5),HED3(5)
C
      DATA HED0/'**ECHO G','ROUND TE','STING IN','PUT PARA','METERS**'/
      DATA HED1/'CONTROL ',' WORDS  ','        ','        ','        '/
      DATA HED2/'INPUT   ','PARAMETE','RS      ','        ','        '/
      DATA HED3/'DIRECTIO','N COSINE',' AND ACC','. VECTOR','        '/
C
      ILINE=0
C
      CALL HVAL(HED0)
      CALL HVAL(HED1)
      CALL IVAL('IGRUND  ',6,IGRUND,0,0,0)
      CALL IVAL('IALTUD  ',6,IALTUD,0,0,0)
      CALL IVAL('IGASBR  ',6,IGASBR,0,0,0)
C
      CALL HVAL(HED2)
      CALL FVAL('ALFAEG  ',6,ALFAEG,0,0,0)
      CALL FVAL('DELTAG  ',6,DELTAG,0,0,0)
      CALL FVAL('PHASEG  ',6,PHASEG,0,0,0)
      CALL FVAL('OMGY    ',4,OMGY,3,0,1)
      CALL FVAL('GLOCAT  ',6,GLOCAT,3,0,1)
      IF(IALTUD.EQ.1) CALL FVAL('ALTUDE  ',6,ALTUDE,0,0,0)
C
C
      CALL HVAL(HED3)
      CALL FVAL('GMAX    ',4,GMAX,3,3,2)
      CALL FVAL('GACC    ',4,GACC,3,0,1)
C
      RETURN
      END
