      SUBROUTINE ETACAL(RSUM,K)
C
C     'ETACAL' CALCULATES THE COMPONENTS OF MOMENTS OF LINEAR
C     MOMENTUM OF EACH ANTENNA ELEMENT IN THE BODY FRAME
C
      IMPLICIT REAL * 8 (A-H,O-Z)
C
      COMMON/RNRGY1/ ZF(3),ZT(3),YOZ(3),YT(3),FC(3,3),YF(3),YFYF(3,3),
     .               YY(3,3)
C
      COMMON/RXCAL / XI(3),XID(3),XX(3,3),XXD(3,3),XDXD(3,3)
C
      DIMENSION RSUM(3),RF(3),RO(3),YDTF(3),X(3)
C
C
      CALL MULTM(FC,XID,YDTF,3,1,3)
      RO(1)=YOZ(2)*YDTF(3) - YOZ(3)*YDTF(2)
      RO(2)=YOZ(3)*YDTF(1) - YOZ(1)*YDTF(3)
      RO(3)=YOZ(1)*YDTF(2) - YOZ(2)*YDTF(1)
C
      X(1)=XXD(2,3) - XXD(3,2)
      X(2)=XXD(3,1) - XXD(1,3)
      X(3)=XXD(1,2) - XXD(2,1)
C
      CALL MULTM(FC,X,RF,3,1,3)
      CALL MSUM(RO,RF,RSUM,3)
C
      RETURN
      END
