      FUNCTION FUNA(K,K1,I)
C
C     'FUNA' EQUIVALENCES ANTENNA TIP DISPLACEMENTS AND VELOCITIES TO
C     OTHER FORTRAN SYMBOLS FOR THE HAMILTONIAN CALCULATIONS.  ENTRY
C     POINTS ARE ADFUN,BDFUN,FUNB
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
C
      COMMON/CANTNA/ A(10,3),ADOT(10,3),B(10,3),BDOT(10,3),DIN(10,3),
     .               DINDOT(10,3),DOUT(10,3),DOUTDT(10,3)
C
      COMMON/MRANG/ ADDOT(10,3),BDDOT(10,3),DOUTDD(10,3),DINDD(10,3)
C
      L=K-K1
      IF(L.GT.0) GO TO 10
      FUNA=DIN(K,I)
      RETURN
   10 FUNA=A(L,I)
      RETURN
C
      ENTRY FUNB(K,K1,I)
C
      L=K-K1
      IF(L.GT.0) GO TO 20
      FUNB=DOUT(K,I)
      RETURN
   20 FUNB=B(L,I)
      RETURN
C
      ENTRY ADFUN(K,K1,I)
C
      L=K-K1
      IF(L.GT.0) GO TO 30
      ADFUN=DINDOT(K,I)
      RETURN
   30 ADFUN=ADOT(L,I)
      RETURN
C
      ENTRY BDFUN(K,K1,I)
C
      L=K-K1
      IF(L.GT.0) GO TO 40
      BDFUN=DOUTDT(K,I)
      RETURN
   40 BDFUN=BDOT(L,I)
      RETURN
C
      ENTRY ADDFUN(K,K1,I)
      L=K-K1
      IF (L.GT.0) GO TO 50
      ADDFUN=DINDD(K,I)
      RETURN
C
   50 ADDFUN=ADDOT(L,I)
      RETURN
C
      ENTRY BDDFUN(K,K1,I)
      L=K-K1
      IF(L.GT.0) GO TO 60
      BDDFUN=DOUTDD(K,I)
      RETURN
C
   60 BDDFUN=BDDOT(L,I)
      RETURN
      END
