      SUBROUTINE GMDINT
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/ADDMOM/H1(3),H2(3),H3(3),HTIP(3)
C
      COMMON/ADSTAT/DER(150),DEP(150)
C
      COMMON/CGIMBD/ELIN(3,3),ELAX(3),ELCG(3),ELMS,ELYY(3,3)
C
      COMMON/CONSTS/PI,TWOPI,RADIAN
C
      COMMON/DMBICS/ELEVI,ELEVID,GMUP(2),GMDN(2)
C
      COMMON/GMBDUT/AZ,AZD,EL,ELD,B(3,3),B0(3,3),B0B(3,3)
C
      COMMON/IGIMBD/IGMBL,NELEV,NE1
C
      COMMON/XIN4  /UP(150),DN(150),BNDS(22)
C
C
      DIMENSION JJ(3),KK(3)
C
      DATA JJ/2,3,1/,KK/3,1,2/
      DO 2 I=1,3
      H1(I)=0.0D0
      H2(I)=0.0D0
      H3(I)=0.0D0
      HTIP(I)=0.0D0
    2 CONTINUE
C
C
      IF(IGMBL.EQ.0) RETURN
C
      DO 5 I=1,3
      J=JJ(I)
      K=KK(I)
      WSI=ELMS*ELCG(I)
      ELYY(I,I)=0.5D0*(ELIN(J,J)+ELIN(K,K)-ELIN(I,I))
      ELYY(I,J)=ELIN(I,J)
      ELYY(I,K)=ELIN(I,K)
    5 CONTINUE
C
      EL=ELEVI*RADIAN
      ELD=ELEVID*RADIAN
C
      NE1=NELEV+1
      DEP(NELEV)=EL
      DEP(NE1)=ELD
C
      UP(NELEV)=GMUP(1)
      DN(NELEV)=GMDN(1)
      UP(NE1)=GMUP(2)
      DN(NE1)=GMDN(2)
C
      RETURN
C
      END
