      SUBROUTINE GPPLOT(BUFF,INDEX)
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      REAL*4 BUFF(450)
C
C
      COMMON/IPOOL1/ IGRAV,IDAMP,IK,K1,ITIM,IAB,IAPS,IBB,IBPS,
     1               NK(10),LK(10),LLK(10)
C
      COMMON/PLTCOM/ IPLMOD,IKMOD
C
      COMMON/RPOOL9/ DUM01(97),ALP(7,7),DUM02(1440)
C
      COMMON/SLANTN/ AP(10,3),APD(10,3),BP(10,3),BPD(10,3),
     1               SAP(10),SAPD(10),SBP(10),SBPD(10)
C
C     SYSTEM PRODUCTS OF INERTIA  INDEX = 248
C
      BUFF(INDEX)=-ALP(4,5)
      BUFF(INDEX+1)=-ALP(4,6)
      BUFF(INDEX+2)=-ALP(5,6)
      INDEX=INDEX+3
C
C     PLOTTED OUTPUT FOR TIP SLOPES
C
      IND=INDEX-1
      IND1=IND+20
C
      DO 20 I=1,IK
      M=NK(I)
      IF(I.GT.K1) GO TO 10
      IF(M.EQ.0) GO TO 8
      BUFF(IND+1)=SAP(I)
      BUFF(IND+2)=SBP(I)
    8 CONTINUE
      IND=IND+2
      GO TO 20
C
   10 CONTINUE
C
      IF(M.EQ.0) GO TO 18
      BUFF(IND1+1)=SAP(I)
      BUFF(IND1+2)=SBP(I)
   18 CONTINUE
      IND1=IND1+2
   20 CONTINUE
C
C
      INDEX=INDEX+40
C
      IND=INDEX-1
C
      IF(IPLMOD.EQ.0) GO TO 40
      DO 30 I=1,IK
      IF(IKMOD.NE.I) GO TO 30
      M=NK(I)
      IF(M.EQ.0) GO TO 40
      DO 25 J=1,M
      BUFF(IND+1)=AP(I,J)
      BUFF(IND+2)=BP(I,J)
      IND=IND+2
   25 CONTINUE
      GO TO 40
   30 CONTINUE
C
   40 CONTINUE
C
      INDEX=INDEX+6
C
      INDEX = 297
C
      CALL GMBPLT(BUFF,INDEX)
      INDEX = 301
      CALL PCSWRP(BUFF,INDEX)
      INDEX = 310
      CALL DMBPLT(BUFF,INDEX)
      INDEX = 314
      CALL DCSWRP(BUFF,INDEX)
      INDEX = 323
      CALL WHPLOT(BUFF,INDEX)
      INDEX = 329
      CALL AWPLOT(BUFF,INDEX)
      INDEX = 331
      CALL THPLOT(BUFF,INDEX)
      INDEX = 341
      CALL SAGPLT(BUFF,INDEX)
      INDEX = 343
      CALL SAPWRP(BUFF,INDEX)
      INDEX = 349
      CALL ADMWRP(BUFF,INDEX)
      INDEX = 358
      CALL TRQPLT(BUFF,INDEX)
      INDEX = 364
C
C     THE VALUE OF INDEX WAS ADJUSTED AS OF DEC 04  IE 364
C
      RETURN
C
      END
