      SUBROUTINE J3CAL(ZBZK,YT,YOZ,YF,YFYF,FM1,RHOKLK,IXDB)
C
C     'J3CAL' IS THE CROSS COUPLING INERTIA MATRIX BETWEEN THE
C     LIBRATION DAMPER ANGULAR VELOCITY AND THE SATELLITE ANGULAR
C     VELOCITY
C
      IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 IXDB(3,3)
C
      DIMENSION ZBZK(3),YT(3),YOZ(3),YF(3),YFYF(3,3),FM1(3,3),
     .          YR(3),YRYT(3,3),YFYO(3,3),YDB(3,3)
C
C
      CALL MULTM(FM1,ZBZK,YR,3,1,3)
C
      DO 10 I=1,3
      DO 10 J=1,3
      YRYT(I,J)=YR(I)*YT(J)
      YFYO(I,J)=YF(I)*YOZ(J)
   10 YDB(I,J)=YRYT(I,J) + YFYO(I,J) + YFYF(I,J)
C
      IXDB(1,1)=IXDB(1,1) + RHOKLK*(YDB(2,2) + YDB(3,3))
      IXDB(2,2)=IXDB(2,2) + RHOKLK*(YDB(3,3) + YDB(1,1))
      IXDB(3,3)=IXDB(3,3) + RHOKLK*(YDB(1,1) + YDB(2,2))
C
      IXDB(1,2)=IXDB(1,2) - RHOKLK*YDB(1,2)
      IXDB(1,3)=IXDB(1,3) - RHOKLK*YDB(1,3)
      IXDB(2,3)=IXDB(2,3) - RHOKLK*YDB(2,3)
C
      IXDB(2,1)=IXDB(2,1) - RHOKLK*YDB(2,1)
      IXDB(3,1)=IXDB(3,1) - RHOKLK*YDB(3,1)
      IXDB(3,2)=IXDB(3,2) - RHOKLK*YDB(3,2)
C
      RETURN
      END
