      SUBROUTINE NUMGPE(NUMEQS)
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/IGIMBL/ IGMBL,NAZIM,NELEV,NA1,NE1
C
      COMMON/IGIMBD/ IGMBLD,NDLEV,ND1
C
      COMMON/IRSTGM/ IGMRST,IARST(3),IRSCY(3)
C
      COMMON/ISAGIM/ ISAGM,NSAGM,NSA1
C
      IF(IGMBL.EQ.0) GO TO 10
C
      IF(IGMRST.NE.0) GO TO 10
C
      NAZIM=NUMEQS+1
      NELEV=NAZIM+2
      NUMEQS=NUMEQS+4
C
   10 CONTINUE
C
      IF(IGMBLD.EQ.0) GO TO 20
C
      NDLEV=NUMEQS+1
      NUMEQS=NUMEQS+2
C
   20 CONTINUE
C
      IF(ISAGM.EQ.0) GO TO 30
C
      NSAGM=NUMEQS+1
      NUMEQS=NUMEQS+2
C
   30 CONTINUE
C
      CALL NUMDCS(NUMEQS)
C
      CALL NUMSAP(NUMEQS)
C
      CALL NUMTHR(NUMEQS)
C
      CALL NUMVDE(NUMEQS)
C
      CALL NUMWHS(NUMEQS)
C
      CALL NUMAMW(NUMEQS)
C
      RETURN
C
      END
