      FUNCTION OFFSTA(K,K1,I)
C
C     'OFFSTA' IS A FUNCTION WHICH DEFINES THE ZERO STRAIN CONDITION
C     IN THE 'A' DIRECTION FOR AN ANTENNA DISPLACEMENT.
C     'OFFSTB' IS A FUNCTION WHICH DEFINES THE ZERO STRAIN CONDITION IN
C     THE 'B' DIRECTION FOR AN ANTENNA DISPLACEMENT.
C
      IMPLICIT REAL*8 (A-H,O-Z)
      OFFSTA=0.0D0
      RETURN
C
      ENTRY OFFSTB(K,K1,J)
      OFFSTB=0.0D0
      RETURN
      END
