      SUBROUTINE PINTRP(XNOW,XDNOW,T)
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
C                  'PINTRP' INTERPOLATES ORBITAL DATA FROM THE
C                  EPHEMERIS TAPE WHICH IS AT MINUTE INTERVALS
C
      COMMON/SATPOS/ TLAST,TFRST,XLAST(3),XFRST(3),XDLAST(3),XDFRST(3),
     .               SDLAST(3),SDFRST(3),ADLAST(3),ADFRST(3),XDT
C
      DIMENSION XNOW(3),XDNOW(3)
C
      DT = TLAST-TFRST
      DTC = T-TFRST
      DO 7 I = 1,3
      IF( DABS     (XFRST(I) - XLAST(I)) -1.0E-10) 5,5,6
    5 XNOW(I) = XFRST(I)
      GO TO 7
    6 SLOPE = (XLAST(I) - XFRST(I))/DT
      XNOW(I) = SLOPE*DTC+XFRST(I)
    7 CONTINUE
      DO 8 I = 1,3
      IF( DABS     (XDFRST(I) - XDLAST(I))-1.0E-10) 9,9,10
    9 XDNOW(I) = XDFRST(I)
      GO TO 8
   10 SLOPE = (XDLAST(I) - XDFRST(I))/DT
      XDNOW(I) = SLOPE*DTC + XDFRST(I)
    8 CONTINUE
      RETURN
      END
