      FUNCTION QTIME(DECDAY)
      IMPLICIT REAL*8(A-H,O-Z)
C     CALCULATES SECOND OF THE CURRENT DAY FROM DECIMAL PART OF
C     SIMULATOR TIME
C
      IDAY=DECDAY
      DAY=IDAY
      QTIME=(DECDAY-DAY)*8.64D4
      RETURN
      END
