      SUBROUTINE READER
C
        IMPLICIT REAL*8 (A-H,O-Z)
      REAL*8 NSUBX,JARRAY,ISUBD
      INTEGER*4 ACNTRL
C
C                       CALLS SETUP FOR ALL VARIABLES TO BE READ IN
C
      COMMON/ANTENA/ A(10,3),ADOT(10,3),B(10,3),BDOT(10,3),DIN(10,3),
     .               DINDOT(10,3),DOUT(10,3),DOUTDT(10,3),ZBZ(3,10),
     .               NELMTS,NDAMPR,MODES(10)
C
      COMMON/CCNVRT/ BDYMI(3,3),DPRMI(3,3),EMODLS(10),RTUBE(10),
     .               HTUBE(10),THERMC(10),TIPMS(10),C(10)
C
      COMMON/CFNALP/ SCO,CIZO(3,3),CIYO(3,3),DONA(3,10),DONB(3,10)
     .              ,CDAMP(3,10)
C
      COMMON/CRATIO/ RATIO
C
      COMMON/CSOLAR/ SAO(10),SKA(9),SKB(9),SKOA(10,3),SKOB(10,3),
     .               STMK(10),SKAA(10,9),SKBB(10,9)
C
      COMMON/CSTVAL/ TSTART,ZL0(10),ZL1(10),ZL2(10),ZLA(10)
C
      COMMON/DMMNT1/ ZKBM(6),FMAK(10),FMBK(10),ARTETA(3),CMTORK(3),
     .               ITORK,IBENDM,ITENSE,ITNS1
C
      COMMON/IMAIN1/ IDATE,LSAVE,INOPT,IPLOT,NUMEQS,IPLTPE,IORB,ITAPE
C
      COMMON/IPOOL1/ IGRAV,IDAMP,IK,K1,ITIM,IAB,IAPS,IBB,IBPS,NK(10),
     .               LK(10),LLK(10)
C
      COMMON/ISHADE/ IPLANS,ISATSH,IWRTTF
C
C
      COMMON/IKPLR/IKPLER
      COMMON/IPRYRT/IPRY
      COMMON/JBTEST/ IBTEST
C
      COMMON/LIBDPR/ZK1D,ZK2D,PHIS,PHILD,DPHILD,BETLD,GAMLD,ZMDO,
     *              ZMDBO,CNV,DECAY
C
      COMMON/MOMENT/ ACNTRL,IVISCS,IATTDE,IMGMTS,IWHEEL,NPULSE
C
      COMMON/NODER / NDER,NOPT
C
      COMMON/PLANSH/ OCCRIT,TAUPL
C
      COMMON/PLOTIT/ XMIN(11),XMAX(11),YMIN(11),YMAX(11),IFSCAL,
     .               KPLOTS(253)
C
      COMMON/PLTCOM/IPLMOD,IKMOD
C
      COMMON/PRESUR/ DTOO,POO
      COMMON/PRYRAT/PRAT,RRAT,YRAT
C
C
      COMMON/PWHEEL/ XMOMIN(3),DVMOM(3),VMOM(3)
C
      COMMON/RATTDE/ DTMXA,PXI,PXO,EIT,REFTIM,TMX1,TMX2,CMX,ISW
C
      COMMON/RMAIN1/ DELTAT,FACTOR,FREQ,TSTOP,DELMIT,
     .               UPBND(150),DNBND(150)
C
      COMMON/RMGNTC/ SMAGI(3),DPMAG(3),SFMAG,MAGFLD
C
      COMMON/RPOOL1/ RHOK(10),TIME,SA(3,3),FM1(3,3),ZLK(10),OMEG(3),
     .               ZLKP(10),ZLKDP(10),CMAT(3,3),GBAR(3,3),YBCM(3),
     .               ZBZK(3,10),FCM(3,3),DTO,PHID,PHI
C
      COMMON/RPOOL2/ PO,SD(3),DAN(3,10),DBN(3,10),CFMT(3,3),DIY1(3),
     .               SD1(3),DT1,P1,AERO,DTO1,YIZK(3),PO1
C
      COMMON/RPOOL3/ ZMS,YIZM(3,2)
C
      COMMON/RTDIST/ TDIS(10)
C
      COMMON/RUNOUT/ LCPU
C
      COMMON/RVISCS/ NSUBX(3),YARRAY(3),RADTBE,VISCTY,RADRNG,DENSTY,
     .               JARRAY(3),SSUBY,OMEGL,ISUBD
C
      COMMON/SATLSH/ TAUK(10),OCULTK(10),RADSH
C
      COMMON/TJAN1/ T
C
      COMMON/XIN1  / PSI1,THET1,PHI1,ETTA,ZETTA,ITEST1
C
      COMMON/XIN2  / ALFAE,BETAE,GAMAE,OMBC(3),ITEST2
C
      COMMON/XIN3  / ALFAEK(10),BETAEK(10),GAMAEK(10),ETTAD,ZETTAD
C
C
C
C
C                       CALL SETUP FOR LABELED COMMON ANTENA
C
      CALL SETUP(8HA       ,8,A,10,3)
      CALL SETUP(8HADOT    ,8,ADOT,10,3)
      CALL SETUP(8HB       ,8,B,10,3)
      CALL SETUP(8HBDOT    ,8,BDOT,10,3)
      CALL SETUP(8HDIN     ,8,DIN,10,3)
      CALL SETUP(8HDINDOT  ,8,DINDOT,10,3)
      CALL SETUP(8HDOUT    ,8,DOUT,10,3)
      CALL SETUP(8HDOUTDT  ,8,DOUTDT,10,3)
      CALL SETUP(8HZBZ     ,8,ZBZ,3,10)
      CALL SETUP(8HNELMTS  ,4,NELMTS)
      CALL SETUP(8HNDAMPR  ,4,NDAMPR)
      CALL SETUP(8HMODES   ,4,MODES,10)
C
C                       CALL SETUP FOR LABELED COMMON CCNVRT
C
      CALL SETUP(8HBDYMI   ,8,BDYMI,3,3)
      CALL SETUP(8HDPRMI   ,8,DPRMI,3,3)
      CALL SETUP(8HEMODLS  ,8,EMODLS,10)
      CALL SETUP(8HRTUBE   ,8,RTUBE,10)
      CALL SETUP(8HHTUBE   ,8,HTUBE,10)
      CALL SETUP(8HTHERMC  ,8,THERMC,10)
      CALL SETUP(8HTIPMS   ,8,TIPMS,10)
      CALL SETUP(8HC       ,8,C,10)
C
C                       CALL SETUP FOR LABELED COMMON CFNALP
C
       CALL SETUP(8HSCO     ,8,SCO)
      CALL SETUP(8HCDAMP   ,8,CDAMP,3,10)
C
C                       CALL SETUP FOR LABELED COMMON CRATIO
C
      CALL SETUP(8HRATIO   ,8,RATIO)
C
C                       CALL SETUP FOR LABELED COMMON CSOLAR
C
       CALL SETUP(8HSAO     ,8,SAO,10)
       CALL SETUP(8HSKOA    ,8,SKOA,10,3)
       CALL SETUP(8HSKOB    ,8,SKOB,10,3)
       CALL SETUP(8HSTMK    ,8,STMK,10)
C
C                       CALL SETUP FOR LABELED COMMON CSTVAL
C
       CALL SETUP(8HZL0     ,8,ZL0,10)
       CALL SETUP(8HZL1     ,8,ZL1,10)
      CALL SETUP(8HZLA     ,8,ZLA,10)
C
C                       CALL SETUP FOR LABELED COMMON DMMNT1
C
      CALL SETUP('IBENDM  ',4,IBENDM)
      CALL SETUP('ITENSE  ',4,ITENSE)
      CALL SETUP('ITORK   ',4,ITORK)
      CALL SETUP('CMTORK  ',8,CMTORK,3)
      CALL SETUP('ZKBM    ',8,ZKBM,6)
C
C                       CALL SETUP FOR LABELED COMMON IMAIN1
C
      CALL SETUP(8HIDATE   ,4,IDATE)
      CALL SETUP(8HINOPT   ,4,INOPT)
      CALL SETUP(8HIPLOT   ,4,IPLOT)
      CALL SETUP(8HIPLTPE  ,4,IPLTPE)
      CALL SETUP(8HIIORB   ,4,IORB)
      CALL SETUP(8HITAPE   ,4,ITAPE)
C
C                       CALL SETUP FOR LABELED COMMON IPOOL1
C
      CALL SETUP('IGRAV   ',4,IGRAV)
      CALL SETUP('IDAMP   ',4,IDAMP)
      CALL SETUP('LK      ',4,LK,10)
      CALL SETUP('LLK     ',4,LLK,10)
C
C                       CALL SETUP FOR LABELED COMMON ISHADE
C
      CALL SETUP('IPLANS  ',4,IPLANS)
      CALL SETUP('ISATSH  ',4,ISATSH)
      CALL SETUP('IWRTTF  ',4,IWRTTF)
C
C                       CALL SETUP FOR LABELED COMMON JBTEST
C
      CALL SETUP(8HIBTEST  ,4,IBTEST)
C
C                       CALL SETUP FOR LABELED COMMON LIBDPR
C
      CALL SETUP(8HPHILD   ,8,PHILD)
      CALL SETUP(8HDPHILD  ,8,DPHILD)
      CALL SETUP(8HGAMLD   ,8,GAMLD)
      CALL SETUP(8HZMDO    ,8,ZMDO)
       CALL SETUP(8HZMDBO   ,8,ZMDBO)
      CALL SETUP(8HDECAY   ,8,DECAY)
      CALL SETUP(8HCNV     ,8,CNV)
       CALL SETUP(8HZK1D    ,8,ZK1D)
       CALL SETUP(8HZK2D    ,8,ZK2D)
       CALL SETUP(8HPHIS    ,8,PHIS)
      CALL SETUP(8HBETLD   ,8,BETLD)
C
C                       CALL SETUP FOR LABELED COMMON MOMENT
      CALL SETUP(8HIVISCS  ,4,IVISCS)
      CALL SETUP(8HIATTDE  ,4,IATTDE)
      CALL SETUP(8HIMGMTS  ,4,IMGMTS)
      CALL SETUP(8HIWHEEL  ,4,IWHEEL)
      CALL SETUP(8HNPULSE  ,4,NPULSE)
C
C                       CALL SETUP FOR LABELED COMMON NODER
C
      CALL SETUP ('NOPT    ',4,NOPT)
C
C                       CALL SETUP FOR LABELED COMMON PLANSH
C
      CALL SETUP('OCCRIT  ',8,OCCRIT)
      CALL SETUP('TAUPL   ',8,TAUPL)
C
C                       CALL SETUP FOR LABELED COMMON PLOTIT
C
      CALL SETUP ('XMIN    ',8,XMIN,11)
      CALL SETUP ('XMAX    ',8,XMAX,11)
      CALL SETUP ('YMIN    ',8,YMIN,11)
      CALL SETUP ('YMAX    ',8,YMAX,11)
      CALL SETUP ('IFSCAL  ',4,IFSCAL)
      CALL SETUP(8HKPLOTS  ,4,KPLOTS,253)
      CALL SETUP ('IPLMOD  ',4,IPLMOD)
      CALL SETUP ('IKMOD   ',4,IKMOD)
C
C                       CALL SETUP FOR LABELED COMMON PRESUR
C
       CALL SETUP(8HDTOO    ,8,DTOO)
       CALL SETUP(8HPOO     ,8,POO)
C
C                       CALL SETUP FOR LABELED COMMON PWHEEL
C
      CALL SETUP(8HXMOMIN  ,8,XMOMIN,3)
      CALL SETUP(8HVMOM    ,8,VMOM,3)
      CALL SETUP(8HDVMOM   ,8,DVMOM,3)
C
C                       CALL SETUP FOR LABELED COMMON RATTDE
C
      CALL SETUP(8HDTMXA   ,8,DTMXA)
      CALL SETUP(8HPXI     ,8,PXI)
      CALL SETUP(8HPXO     ,8,PXO)
      CALL SETUP(8HCMX     ,8,CMX)
C
C
C                       CALL SETUP FOR LABELED COMMON RMAIN1
C
       CALL SETUP(8HDELTAT  ,8,DELTAT)
       CALL SETUP(8HFACTOR  ,8,FACTOR)
       CALL SETUP(8HFREQ    ,8,FREQ)
       CALL SETUP(8HTSTOP   ,8,TSTOP)
       CALL SETUP(8HDELMIT  ,8,DELMIT)
       CALL SETUP(8HUPBND   ,8,UPBND,150)
       CALL SETUP(8HDNBND   ,8,DNBND,150)
C
C                       CALL SETUP FOR LABELED COMMON RMGNTC
C
      CALL SETUP(8HSMAGI   ,8,SMAGI,3)
      CALL SETUP(8HDPMAG   ,8,DPMAG,3)
      CALL SETUP(8HSFMAG   ,8,SFMAG)
      CALL SETUP(8HMAGFLD  ,4,MAGFLD)
C
C                       CALL SETUP FOR LABELED COMMON RPOOL1
C
       CALL SETUP(8HRHOK    ,8,RHOK,10)
      CALL SETUP(8HTIME    ,8,T)
      CALL SETUP(8HOMEG    ,8,OMEG,3)
C
C                       CALL SETUP FOR LABELED COMMON RPOOL2
C
      CALL SETUP(8HAERO    ,8,AERO)
      CALL SETUP(8HDTO1    ,8,DTO1)
      CALL SETUP(8HPO1     ,8,PO1)
C
C                       CALL SETUP FOR LABELED COMMON RPOOL3
C
       CALL SETUP(8HYIZM    ,8,YIZM,3,2)
C
C                       CALL SETUP FOR LABELED COMMON RTDIST
C
      CALL SETUP(8HTDIS    ,8,TDIS,10)
C
C                       CALL SETUP FOR LABELED COMMON RUNOUT
C
      CALL SETUP(8HLCPU    ,4,LCPU)
C
C                       CALL SETUP FOR LABELED COMMON RVISCS
C
      CALL SETUP(8HNSUBX   ,8,NSUBX,3)
      CALL SETUP(8HYARRAY  ,8,YARRAY,3)
      CALL SETUP(8HRADTBE  ,8,RADTBE)
      CALL SETUP(8HVISCTY  ,8,VISCTY)
      CALL SETUP(8HRADRNG  ,8,RADRNG)
      CALL SETUP(8HDENSTY  ,8,DENSTY)
      CALL SETUP(8HJARRAY  ,8,JARRAY,3)
      CALL SETUP(8HOMEGL   ,8,OMEGL)
C
C                       CALL SETUP FOR LABELED COMMON SATLSH
C
      CALL SETUP('TAUK    ',8,TAUK,10)
      CALL SETUP('OCULTK  ',8,OCULTK,10)
      CALL SETUP('RADSH   ',8,RADSH)
C
C                       CALL SETUP FOR LABELED COMMON TJAN1
C
      CALL SETUP('TIME    ',8,T)
C
C                       CALL SETUP FOR LABELED COMMON XIN1
C
      CALL SETUP(8HPSI1    ,8,PSI1)
      CALL SETUP(8HTHET1   ,8,THET1)
      CALL SETUP(8HPHI1    ,8,PHI1)
      CALL SETUP(8HETTA    ,8,ETTA)
      CALL SETUP(8HZETTA   ,8,ZETTA)
C
C                       CALL SETUP FOR LABELED COMMON XIN2
C
      CALL SETUP(8HALFAE   ,8,ALFAE)
      CALL SETUP(8HBETAE   ,8,BETAE)
      CALL SETUP(8HGAMAE   ,8,GAMAE)
C
      CALL SETUP('IPRY    ',4,IPRY)
      CALL SETUP(8HPRAT    ,8,PRAT)
      CALL SETUP(8HRRAT    ,8,RRAT)
      CALL SETUP(8HYRAT    ,8,YRAT)
C   END OF COMMON BLOCK PRYRAT
      CALL SETUP(8HOMBC    ,8,OMBC,3)
C                       CALL SETUP FOR LABELED COMMON XIN3
C
      CALL SETUP(8HALFAEK  ,8,ALFAEK,10)
      CALL SETUP(8HBETAEK  ,8,BETAEK,10)
      CALL SETUP(8HGAMAEK  ,8,GAMAEK,10)
      CALL SETUP(8HZETTAD  ,8,ZETTAD)
      CALL SETUP(8HETTAD   ,8,ETTAD)
C
C
      CALL READZ
      RETURN
      END
