      FUNCTION ROFUN(RO,OM,YT)
C
C     'ROFUN' IS A FUNCTION TO EVALUATE A TERM IN THE CALCULATION
C     OF THE INERTIAL VELOCITY OF THE CENTER OF MASS.
C
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION RO(3),OM(3),YT(3)
      RO(1)=OM(2)*YT(3)-OM(3)*YT(2)
      RO(2)=OM(3)*YT(1)-OM(1)*YT(3)
      RO(3)=OM(1)*YT(2)-OM(2)*YT(1)
      ROFUN=1.0D0
      RETURN
      END
