      SUBROUTINE SBDINF(ANG2,ANG2D,TRKS,TRKD)
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/SBINTF/SBK1(3),SBK2(3),SBSTA(3),SBDM(3)
C
C
      DIMENSION ANG2(3),ANG2D(3),TRKS(3),TRKD(3)
C
C
      DO 10 I=1,3
      TRKD(I)=SBDM(I)*ANG2D(I)
C
      ARG=ANG2(I)
      AMAG=DABS(ARG)
      ALIM=SBSTA(I)
      IF(AMAG.GT.ALIM) GO TO 5
      TRKS(I)=SBK1(I)*ARG
      GO TO 10
C
    5 CONTINUE
C
      IF(ARG.LT.0.0D0) ALIM=-ALIM
      TRKS(I)=SBK1(I)*ALIM+SBK2(I)*(ARG-ALIM)
C
   10 CONTINUE
C
C
      RETURN
C
      END
