      SUBROUTINE SECOUT
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/ACFILT/ACPARM(20),IACFLT(20)
C
      COMMON/ACTOUT/SOUT,VOUT,WOUT
C
      COMMON/CONSTS/PI,TWOPI,RADIAN
C
      COMMON/ISECBD/I2BDY
C
      COMMON/SBDOUT/ANG2(3),ANG2D(3),ANG2DD(3),B(3,3),B0B(3,3)
     1             ,OM2(3),SALP,CALP,SBET,CBET,H2B(3)
C
      DATA I5/',A5,'/
      DATA I8/',A8,'/
C
      IF(I2BDY.EQ.0) GO TO 10
      GAMSB=ANG2(1)/RADIAN
      ALPSB=ANG2(2)/RADIAN
      BETSB=ANG2(3)/RADIAN
      CALL SET('GAMSB   ',0,0,GAMSB,I5)
      CALL SET('ALPSB   ',0,0,ALPSB,I5)
      CALL SET('BETSB   ',0,0,BETSB,I5)
      OM1SB=OM2(1)/RADIAN
      OM2SB=OM2(2)/RADIAN
      OM3SB=OM2(3)/RADIAN
      CALL SET('OM1SB   ',0,0,OM1SB,I5)
      CALL SET('OM2SB   ',0,0,OM2SB,I5)
      CALL SET('OM3SB   ',0,0,OM3SB,I5)
C
   10 CONTINUE
C
      IF(IACFLT(1).EQ.0) RETURN
      CALL SET('SEN OUTP',0,0,SOUT,I8)
      CALL SET('FIL OUTP',0,0,VOUT,I8)
C
C
      RETURN
C
      END
