      SUBROUTINE SINPUT(DEPEND)
      IMPLICIT REAL*8 (A-H,O-Z)
C
      COMMON/CONSTS/ PI,TWOPI,RADIAN
C
      COMMON/IPOOL1/ IGRAV,IDAMP,IK,K1,ITIM,IAB,IAPS,IBB,IBPS,NK(10),
     .               LK(10),LLK(10)
C
      COMMON/LIBDPR/ ZK1D,ZK2D,PHIS,PHILD,DPHILD,BETLD,GAMLD,
     .               ZMDO,ZMDBO,CNV,DECAY
C
      COMMON/RPOOL1/ RHOK(10),TIME,SA(3,3),FM1(3,3),ZLK(10),OMEG(3),
     .               ZLKP(10),ZLKDP(10),CMAT(3,3),GBAR(3,3),YBCM(3),
     .               ZBZK(3,10),FCM(3,3),DTO,PHID,PHI
C
      COMMON/RPOOL6/ FM(3,3),CIY(3,3),CIZ(3,3),SAT(3,3),SZ1,SZ2,SZ3
C
      COMMON/XIN1  / PSI1,THET1,PHI1,ETTAE,ZETTA,ITEST1
C
C
C
      DIMENSION DEPEND(150),OMRB(3)
C
      PHI1=PHI1*RADIAN
      PSI1=PSI1*RADIAN
      THET1=THET1*RADIAN
C
      SPHI1=DSIN(PHI1)
      CPHI1=DCOS(PHI1)
      SPSI1=DSIN(PSI1)
      CPSI1=DCOS(PSI1)
      STHET1=DSIN(THET1)
      CTHET1=DCOS(THET1)
C
      ANG1=CPHI1*CPSI1
      ANG2=SPHI1*SPSI1
      ANG3=CPHI1*SPSI1
      ANG4=SPHI1*CPSI1
C
      SA(1,1)= ANG1 - ANG2*CTHET1
      SA(2,1)= ANG3 + ANG4*CTHET1
      SA(3,1)= SPHI1*STHET1
C
      SA(1,2)=-ANG4 - ANG3*CTHET1
      SA(2,2)=-ANG2 + ANG1*CTHET1
      SA(3,2)= CPHI1*STHET1
C
      SA(1,3)= SPSI1*STHET1
      SA(2,3)=-CPSI1*STHET1
      SA(3,3)= CTHET1
C
      DO 10 I=1,3
      OMEG(I)=OMEG(I)*RADIAN
      OMRB(I)=OMEG(I)
      DO 10 J=1,3
   10 SAT(I,J)=SA(J,I)
C
      L=0
      DO 20 I=1,2
      DO 20 J=1,3
      L=L + 1
   20 DEPEND(L)=SA(I,J)
C
      DO 30 I=1,3
      L=I + 6
   30 DEPEND(L)=OMRB(I)
C
      PHI1=PHI1/RADIAN
      PSI1=PSI1/RADIAN
      THET1=THET1/RADIAN
C
      IF(IDAMP.EQ.0) RETURN
      PHI=PHILD*RADIAN
      PHID=DPHILD*RADIAN
      DEPEND(10)=PHI
      DEPEND(11)=PHID
C
      RETURN
      END
