      FUNCTION SPRING(ZK1D,ZK2D,PHI,PHIS,RADIAN)
C
C     'SPRING' IS A FUNCTION THAT EVALUATES THE STRAIN ENERGY OF THE
C     LIBRATION DAMPER SPRING.
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
      PHIR=PHI*RADIAN
      PHISR=PHIS*RADIAN
C
      IF(PHIR.LT.PHISR) GO TO 10
      SPRING=ZK1D*PHISR*PHISR/2 + ZK1D*PHISR*(PHIR - PHISR)
     .                          +(ZK2D/2)*(PHIR - PHISR)**2
      RETURN
C
   10 SPRING=ZK1D*PHIR*PHIR/2
      RETURN
      END
