      FUNCTION STRN(SE,IK)
C
C     'STRN' IS A FUNCTION WHICH SUMS THE STRAIN ENERGY FROM EACH
C     ANTENNA ELEMENT.
C
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION SE(10)
      STRN=0.0D0
      DO 10 K=1,IK
   10 STRN=STRN + SE(K)
      RETURN
      END
