      FUNCTION TWOTBM(K)
C
C     'TWOTBM' IS A FUNCTION WHICH EVALUATES THE RELATIVE KINETIC ENERGY
C     OF AN ELEMENT IN THE ELEMENT FRAME.
C
      IMPLICIT REAL*8 (A-H,O-Z)
C
      COMMON/IPOOL1/ IGRAV,IDAMP,IK,K1,ITIM,IAB,IAPS,IBB,IBPS,NK(10),
     .               LK(10),LLK(10)
C
      COMMON/RPOOL1/ RHOK(10),TIME,SA(3,3),FM1(3,3),ZLK(10),OMEG(3),
     .               ZLKP(10),ZLKDP(10),CMAT(3,3),GBAR(3,3),YBCM(3),
     .               ZBZK(3,10),FCM(3,3),DTO,PHID,PHI
C
      COMMON/RXCAL / XI(3),XID(3),XX(3,3),XXD(3,3),XDXD(3,3)
C
C
      TWOTBM=0.0D0
      RHOKLK=RHOK(K)*ZLK(K)
      SUM=0.0D0
C
      DO 10 I=1,3
   10 SUM=SUM + XDXD(I,I)
C
      TWOTBM=RHOKLK*SUM
C
      RETURN
      END
