      SUBROUTINE VDIC
C      VISCOUS DAMPER INITIAL CONDITIONS
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8 ISUBD,JARRAY,NSUBX
      COMMON /ADSTAT/DER(150),DEP(150)
      COMMON/CONSTS/ PI,TWOPI,RADIAN
      COMMON/IMAIN1/ IDATE,LSAVE,INOPT,IPLOT,NUMEQS,IPLTPE,IORB,ITAPE
      COMMON/RPOOL1/ RHOK(10),TIME,SA(3,3),FM1(3,3),ZLK(10),OMEG(3),
     .               ZLKP(10),ZLKDP(10),CMAT(3,3),GBAR(3,3),YBCM(3),
     .               ZBZK(3,10),FCM(3,3),DTO,PHID,PHI
      COMMON/RVISCS/ NSUBX(3),YARRAY(3),RADTBE,VISCTY,RADRNG,DENSTY,
     .               JARRAY(3),SSUBY,OMEGL,ISUBD
      J=NUMEQS - 4
C
      DO 40 I=1,3
      L=J+I
   40 DEP(L)=YARRAY(I)
C
      ASQR=RADTBE*RADTBE
      BCUBE=RADRNG**3
      ISUBD=2.D0*PI*PI/(12.D0**5*32.174D0)*DENSTY*ASQR*BCUBE
C
      TEMP=0.D0
      DO 45 I=1,3
   45 TEMP=TEMP + OMEG(I)*NSUBX(I)
C
      SSUBY=-ISUBD*(OMEGL*RADIAN + TEMP)
      DEP(NUMEQS)=SSUBY
      RETURN
      END
