$ SET NOVERIFY
$ !
$ ! CAPITALIZE --- REPLACE ANY LOWER CASE LETTERS IN A FILE WITH
$ !                CAPITALS... ALL OTHER CHARACTERS ARE UNCHANGED.
$ !
$ ON WARNING THEN EXIT
$ ON ERROR THEN EXIT
$ IF P1 .NES. "" THEN GOTO POK
$NOP:
$ INQUIRE P1 "Filename"
$ IF P1 .EQS. "" THEN GOTO NOP
$POK:
$ ASSIGN 'P1' FOR007
$ ASSIGN TEMP.CAP FOR008
$ RUN MERLIN:CAPITAL
$ RENAME TEMP.CAP 'P1'
$ DEASSIGN/ALL
