$ SET NOVERIFY
$ !
$ ! COMCLEAN --- COMMON BLOCK CLEANER UPPER.  USED AFTER TIDY.
$ !
$ ON WARNING THEN EXIT
$ ON ERROR THEN EXIT
$ IF P1 .NES. "" THEN GOTO POK
$NOP:
$ INQUIRE P1 "Filename"
$ IF P1 .EQS. "" THEN GOTO NOP
$POK:
$ ASSIGN 'P1'.FOR FOR005
$ ASSIGN TEMP.CLN FOR007
$ RUN MERLIN:CCLEAN
$ RENAME TEMP.CLN 'P1'.FOR
$ DEASSIGN/ALL
