      PARAMETER (MAXCOM=10,MAXVAR=100)
      COMMON / NAME /  NIN,  NOUT,  EOF,  TYPE, STMT, NCOM, LINE, 
     $ CNAMES(MAXCOM),  NUMVAR(MAXCOM),   VNAMES(MAXVAR,MAXCOM), 
     $ VSIZES(MAXVAR,MAXCOM), VTYPES(MAXVAR,MAXCOM), 
     $ VINDEX(MAXVAR,MAXCOM), NSAVE, SIGNAL
      CHARACTER *1500 STMT
      CHARACTER *80 LINE
      CHARACTER *20 CNAMES, VNAMES
      CHARACTER *1 TYPE, VTYPES, SIGNAL
      INTEGER VSIZES, VINDEX
      LOGICAL EOF
