      PARAMETER (MAXCOM=20,MAXVAR=500)
      COMMON / NAMEIN /  NIN,    NOUT,    NSAVE,    EOF,    TYPE,  
     $                   LINE,   STMT,    SIGNAL,   NCHAR,  NCOM,
     $ CNAMES(MAXCOM),           NUMVAR(MAXCOM),   
     $ VNAMES(MAXVAR,MAXCOM),    VSIZES(MAXVAR,MAXCOM), 
     $ VTYPES(MAXVAR,MAXCOM),    VINDEX(MAXVAR,MAXCOM)
      CHARACTER *1500 STMT
      CHARACTER *80 LINE
      CHARACTER *20 CNAMES, VNAMES
      CHARACTER *1 TYPE, VTYPES, SIGNAL
      INTEGER VSIZES, VINDEX
      LOGICAL EOF
