      PROGRAM STRIP72
C*
C*  STRIP72 - REMOVE ALL CHARACTERS BEYOND COLUMN 72...
C*   REMOVE ALL TRAILING BLANKS ON REMAINING LINE.
C*
      CHARACTER *72 LINE
C
      OPEN ( UNIT=8, CARRIAGECONTROL='LIST', STATUS='NEW' )
10    READ ( 7, 900, END=1000 ) LINE
      L = LENGTH ( LINE )
      IF (L .GT. 0) THEN
         WRITE ( 8, 910 ) LINE (1:L)
      ELSE
         WRITE ( 8, 920 ) 
      ENDIF
      GO TO 10
1000  STOP
900   FORMAT( A72 )
910   FORMAT( A )
920   FORMAT(   )
      END
