$ SET NOVERIFY
$ !
$ ! STRIP72 - REMOVE ALL CHARACTERS BEYOND COLUMN 72.
$ !
$ IF P1 .NES. "" THEN GOTO POK
$NOP:
$ INQUIRE P1 "Filename"
$ IF P1 .EQS. "" THEN GOTO NOP
$POK:
$ ASSIGN 'P1'     FOR007
$ ASSIGN TEMP.STR FOR008
$ RUN MERLIN:STRIP72
$ RENAME TEMP.STR 'P1'
$ DEASSIGN/ALL
