$ SET NOVERIFY
$ ON WARNING THEN EXIT
$ ON ERROR THEN EXIT
$ IF P1 .NES. "" THEN GOTO POK
$NOP:
$ INQUIRE P1 "Filename"
$ IF P1 .EQS. "" THEN GOTO NOP
$POK:
$ ASSIGN 'P1' FOR001
$ ASSIGN TEMP.VMS FOR002
$ RUN MERLIN:VMSFORT
$ RENAME TEMP.VMS 'P1'
$ DEASSIGN/ALL
