      PROGRAM VMSFORT
C*
C*     CONVERT A VMS INTERNAL FORMAT FILE TO A FORTRAN FORMAT FILE...
C*      IE, ONE WITH CARRIAGE CONTROL CHARACTERS.
C*
      CHARACTER *132 LINE
      CHARACTER *1 FF, LF
C
      FF = CHAR(12)
      LF = CHAR(10)
10    READ(1,900,END=1000)LINE
      LL = LENGTH ( LINE )
      IF (LL .LT. 2)LL = 2
      IF (LINE(1:1) .EQ. FF) THEN
           WRITE(2,901)LINE(2:LL)
      ELSE IF (LINE(1:1) .EQ. LF) THEN
           WRITE(2,902)LINE(2:LL)
      ELSE
           WRITE(2,903)LINE(1:LL)
      ENDIF
      GO TO 10
C
1000  STOP
900   FORMAT(A)
901   FORMAT('1',A)
902   FORMAT('0',A)
903   FORMAT(' ',A)
      END
